/* =============================================================
   data.js — April 2026 meal data + recipe library
   My Wellness Journey  (tracking Apr 6 – Apr 30, 2026)
   ============================================================= */

(function () {
  'use strict';

  /* ── Protein Shake (every day) ──────────────────────────── */
  const PS = { type: 'Protein Shake', food: 'Premier Protein Café Latte', protein: 30, cal: 160 };

  /* ── Per-day breakfast lookup ───────────────────────────── */
  // Spec-defined breakfasts per date
  const BREAKFASTS = {
    '2026-04-06': { type: 'Breakfast', food: 'Besan ke chille (2) + mint chutney',                protein: 14, cal: 280 },
    '2026-04-07': { type: 'Breakfast', food: 'Overnight oats jar',                                protein: 22, cal: 380 },
    '2026-04-08': { type: 'Breakfast', food: 'Besan ke chille (2) + mint chutney',                protein: 14, cal: 280 },
    '2026-04-09': { type: 'Breakfast', food: 'Overnight oats jar',                                protein: 22, cal: 380 },
    '2026-04-10': { type: 'Breakfast', food: 'Besan ke chille (2) + mint chutney',                protein: 14, cal: 280 },
    '2026-04-11': { type: 'Breakfast', food: 'Masala oats warm bowl',                             protein: 18, cal: 300 },
    '2026-04-12': { type: 'Breakfast', food: 'Smoothie bowl — yogurt + berries + granola',        protein: 20, cal: 380 },
    '2026-04-13': { type: 'Breakfast', food: 'Overnight oats jar',                                protein: 22, cal: 380 },
    '2026-04-14': { type: 'Breakfast', food: 'Besan chille (2) packed',                           protein: 14, cal: 280 },
    '2026-04-15': { type: 'Breakfast', food: 'Overnight oats jar',                                protein: 22, cal: 380 },
    '2026-04-16': { type: 'Breakfast', food: 'Besan chille (2) packed',                           protein: 14, cal: 280 },
    '2026-04-17': { type: 'Breakfast', food: 'Overnight oats jar',                                protein: 22, cal: 380 },
    '2026-04-18': { type: 'Breakfast', food: 'Poha with veggies',                                 protein: 14, cal: 290 },
    '2026-04-19': { type: 'Breakfast', food: 'Oats idli + peanut chutney',                        protein: 18, cal: 310 },
    '2026-04-20': { type: 'Breakfast', food: 'Masala cottage cheese toast on sourdough',          protein: 22, cal: 320 },
    '2026-04-21': { type: 'Breakfast', food: 'Overnight oats jar',                                protein: 22, cal: 380 },
    '2026-04-22': { type: 'Breakfast', food: 'Masala cottage cheese toast on sourdough',          protein: 22, cal: 320 },
    '2026-04-23': { type: 'Breakfast', food: 'Overnight oats jar',                                protein: 22, cal: 380 },
    '2026-04-24': { type: 'Breakfast', food: 'Masala cottage cheese toast on sourdough',          protein: 22, cal: 320 },
    '2026-04-25': { type: 'Breakfast', food: 'Besan ke chille fresh + chai',                      protein: 14, cal: 280 },
    '2026-04-26': { type: 'Breakfast', food: 'Protein pancake stack with Greek yogurt',           protein: 30, cal: 340 },
    '2026-04-27': { type: 'Breakfast', food: 'Smoothie bowl',                                     protein: 20, cal: 380 },
    '2026-04-28': { type: 'Breakfast', food: 'Overnight oats jar',                                protein: 22, cal: 380 },
    '2026-04-29': { type: 'Breakfast', food: 'Overnight oats jar',                                protein: 22, cal: 380 },
    '2026-04-30': { type: 'Breakfast', food: 'Besan ke chille',                                   protein: 14, cal: 280 },
  };

  /* ── Per-day lunch lookup ───────────────────────────────── */
  function lunch(isOffice, isWFH, isWeekend) {
    if (isOffice)  return { type: 'Lunch', food: 'Quinoa veggie bowl — roasted veggies, chickpeas, feta', protein: 22, cal: 480 };
    if (isWFH)     return { type: 'Lunch', food: 'Lentil soup + whole wheat pita',                        protein: 18, cal: 350 };
    return               { type: 'Lunch', food: 'Eat out smart / leftovers',                              protein: 15, cal: 400 };
  }

  /* ── Per-day snack lookup ───────────────────────────────── */
  function snack(isOffice, week, isWFH, isWeekend) {
    if (isOffice && (week === 1 || week === 3)) return { type: 'Snack', food: 'Cottage cheese + cucumber',    protein: 14, cal: 80  };
    if (isOffice && (week === 2 || week === 4)) return { type: 'Snack', food: 'Hummus + veggie sticks',       protein: 5,  cal: 150 };
    if (isWFH)                                  return { type: 'Snack', food: 'Apple + almond butter',        protein: 7,  cal: 200 };
    return                                             { type: 'Snack', food: 'Greek yogurt + berries + granola', protein: 18, cal: 280 };
  }

  /* ── Per-day dinner lookup ──────────────────────────────── */
  const DINNERS = {
    '2026-04-06': { type: 'Dinner', food: 'Paneer tikka wrap + raita',                                                          protein: 28, cal: 510, tip: 'Marinate paneer in the morning before OT for best flavour.' },
    '2026-04-07': { type: 'Dinner', food: 'Dal tadka + brown rice + roti',                                                      protein: 18, cal: 420, tip: 'Make a big batch — enough for Thursday leftovers too.' },
    '2026-04-08': { type: 'Dinner', food: 'Shirataki noodles with tomato lentil marinara and parmesan',                         protein: 22, cal: 310, tip: 'Rinse shirataki noodles very well and dry-fry 2 min before adding sauce — removes the smell.' },
    '2026-04-09': { type: 'Dinner', food: 'Stuffed aloo paratha + Greek yogurt',                                                protein: 18, cal: 520, tip: 'Boil potatoes during Sunday prep to save 15 min tonight.' },
    '2026-04-10': { type: 'Dinner', food: 'Thai peanut shirataki noodle bowl with edamame, cucumber, peanut sauce',             protein: 20, cal: 350, tip: 'Peanut sauce = almond butter + soy sauce + lime + garlic + water — done in 2 min.' },
    '2026-04-11': { type: 'Dinner', food: 'Whole wheat pizza with paneer, bell peppers, mushrooms, low-fat mozzarella',         protein: 24, cal: 480, tip: 'Use a whole wheat tortilla as base — 12 min at 425°F.' },
    '2026-04-12': { type: 'Dinner', food: 'Warm Mediterranean quinoa bowl with chickpeas, roasted veggies, hummus, feta',       protein: 20, cal: 430, tip: 'Everything from Sunday prep — dinner takes 5 min.' },
    '2026-04-13': { type: 'Dinner', food: 'South Indian oats pongal + sambar + peanut chutney',                                 protein: 16, cal: 350, tip: 'Black pepper and ghee tempering makes it taste authentic.' },
    '2026-04-14': { type: 'Dinner', food: 'Shirataki pad thai with paneer, peanuts, bean sprouts, lime',                        protein: 22, cal: 340, tip: 'High heat is the secret — cook on hottest setting.' },
    '2026-04-15': { type: 'Dinner', food: 'Paneer butter masala lite (Greek yogurt instead of cream) + brown rice',             protein: 26, cal: 480, tip: 'Greek yogurt gives same creaminess with far fewer calories.' },
    '2026-04-16': { type: 'Dinner', food: 'Black bean veggie burger wrap with avocado, salsa, cheese',                          protein: 20, cal: 490, tip: 'Make extra patties and freeze for future Fridays.' },
    '2026-04-17': { type: 'Dinner', food: 'Besan adai thick pancakes + sambar + peanut chutney',                                protein: 18, cal: 290, tip: 'Thicker batter, longer cook time gives hearty adai texture.' },
    '2026-04-18': { type: 'Dinner', food: 'Thai green curry with paneer and vegetables over cauliflower rice',                  protein: 24, cal: 420, tip: 'Use store-bought vegetarian green curry paste for speed.' },
    '2026-04-19': { type: 'Dinner', food: 'Dal makhani lite with low-fat dairy + jeera rice',                                   protein: 20, cal: 450, tip: 'Tastes better next day — make extra for Monday lunch.' },
    '2026-04-20': { type: 'Dinner', food: 'Shirataki noodles with walnut basil pesto and roasted cherry tomatoes',              protein: 18, cal: 340, tip: 'Blend basil, walnuts, parmesan, olive oil, garlic — better than jar pesto.' },
    '2026-04-21': { type: 'Dinner', food: 'Masala dosa filling (aloo masala) in whole wheat crepes + coconut chutney',          protein: 16, cal: 380, tip: 'Use besan chille as crepe base if no dosa batter.' },
    '2026-04-22': { type: 'Dinner', food: 'Paneer stir fry with bell peppers and soy-ginger sauce over brown rice',             protein: 26, cal: 440, tip: 'High heat, quick toss — don\'t overcook paneer.' },
    '2026-04-23': { type: 'Dinner', food: 'Chole chickpea curry + brown rice',                                                  protein: 18, cal: 420, tip: 'Canned chickpeas work perfectly — rinse well.' },
    '2026-04-24': { type: 'Dinner', food: 'Oats idli + sambar + peanut chutney',                                                protein: 18, cal: 310, tip: 'Fresh peanut chutney batch if needed.' },
    '2026-04-25': { type: 'Dinner', food: 'Thai massaman curry with paneer and potatoes over cauliflower rice',                 protein: 22, cal: 430, tip: 'Massaman is the mildest Thai curry — creamy, slightly sweet, non-spicy.' },
    '2026-04-26': { type: 'Dinner', food: 'Palak paneer lite + roti + small brown rice',                                        protein: 26, cal: 460, tip: 'Blanch and blend spinach first for deep green restaurant colour.' },
    '2026-04-27': { type: 'Dinner', food: 'Chole stuffed whole wheat quesadilla with cheese and Greek yogurt dip',              protein: 24, cal: 450, tip: 'Press down with spatula while cooking for crispier result.' },
    '2026-04-28': { type: 'Dinner', food: 'Shirataki noodles with roasted garlic Greek yogurt cream sauce, spinach and paneer', protein: 24, cal: 370, tip: 'Yogurt cream sauce = Greek yogurt + roasted garlic + parmesan + pasta water.' },
    '2026-04-29': { type: 'Dinner', food: 'South Indian tomato rice + cucumber raita + papad',                                  protein: 16, cal: 360, tip: 'Tomato rice done in 20 min and tastes great cold next day.' },
    '2026-04-30': { type: 'Dinner', food: 'Shirataki noodles with avocado pesto, cherry tomatoes and feta',                     protein: 16, cal: 340, tip: 'Avocado pesto = avocado + basil + lemon + parmesan blended — no cooking.' },
  };

  /* ── April 2026 schedule (tracking starts Apr 6, Monday) ── */
  // Office: Tue/Wed/Thu | WFH: Mon/Fri | Weekend: Sat/Sun
  // OT: Mon/Fri = 7:30am, Tue/Wed/Thu = 4:30pm, Sat/Sun = none
  const APRIL_DAYS_META = [
    // [date,         dayNum, dow,   short,     week, office, wfh,   wknd,  ot,    otTime]
    ['2026-04-06',  1, 'Mon', 'Apr 6',   1, false, true,  false, true,  '7:30am'],
    ['2026-04-07',  2, 'Tue', 'Apr 7',   1, true,  false, false, true,  '4:30pm'],
    ['2026-04-08',  3, 'Wed', 'Apr 8',   1, true,  false, false, true,  '4:30pm'],
    ['2026-04-09',  4, 'Thu', 'Apr 9',   1, true,  false, false, true,  '4:30pm'],
    ['2026-04-10',  5, 'Fri', 'Apr 10',  1, false, true,  false, true,  '7:30am'],
    ['2026-04-11',  6, 'Sat', 'Apr 11',  1, false, false, true,  false, null],
    ['2026-04-12',  7, 'Sun', 'Apr 12',  1, false, false, true,  false, null],
    ['2026-04-13',  8, 'Mon', 'Apr 13',  2, false, true,  false, true,  '7:30am'],
    ['2026-04-14',  9, 'Tue', 'Apr 14',  2, true,  false, false, true,  '4:30pm'],
    ['2026-04-15', 10, 'Wed', 'Apr 15',  2, true,  false, false, true,  '4:30pm'],
    ['2026-04-16', 11, 'Thu', 'Apr 16',  2, true,  false, false, true,  '4:30pm'],
    ['2026-04-17', 12, 'Fri', 'Apr 17',  2, false, true,  false, true,  '7:30am'],
    ['2026-04-18', 13, 'Sat', 'Apr 18',  2, false, false, true,  false, null],
    ['2026-04-19', 14, 'Sun', 'Apr 19',  2, false, false, true,  false, null],
    ['2026-04-20', 15, 'Mon', 'Apr 20',  3, false, true,  false, true,  '7:30am'],
    ['2026-04-21', 16, 'Tue', 'Apr 21',  3, true,  false, false, true,  '4:30pm'],
    ['2026-04-22', 17, 'Wed', 'Apr 22',  3, true,  false, false, true,  '4:30pm'],
    ['2026-04-23', 18, 'Thu', 'Apr 23',  3, true,  false, false, true,  '4:30pm'],
    ['2026-04-24', 19, 'Fri', 'Apr 24',  3, false, true,  false, true,  '7:30am'],
    ['2026-04-25', 20, 'Sat', 'Apr 25',  3, false, false, true,  false, null],
    ['2026-04-26', 21, 'Sun', 'Apr 26',  3, false, false, true,  false, null],
    ['2026-04-27', 22, 'Mon', 'Apr 27',  4, false, true,  false, true,  '7:30am'],
    ['2026-04-28', 23, 'Tue', 'Apr 28',  4, true,  false, false, true,  '4:30pm'],
    ['2026-04-29', 24, 'Wed', 'Apr 29',  4, true,  false, false, true,  '4:30pm'],
    ['2026-04-30', 25, 'Thu', 'Apr 30',  4, true,  false, false, true,  '4:30pm'],
  ];

  const APRIL_DAYS = APRIL_DAYS_META.map(([date, dayNum, dow, short, week, isOffice, isWFH, isWeekend, hasOT, otTime]) => {
    const bk = BREAKFASTS[date];
    const ln = lunch(isOffice, isWFH, isWeekend);
    const sn = snack(isOffice, week, isWFH, isWeekend);
    const dn = DINNERS[date];
    return {
      date, dayNum, dow, short, week,
      isOffice, isWFH, isWeekend, hasOT, otTime,
      meals: [bk, PS, ln, sn, dn],
    };
  });

  window.APRIL_DATA = { days: APRIL_DAYS };

  /* ═══════════════════════════════════════════════════════════
     RECIPES — 34 total (25 dinners + 9 breakfasts/lunches)
  ═══════════════════════════════════════════════════════════ */
  window.RECIPES = [

    /* ── BREAKFAST RECIPES ─────────────────────────────────── */
    {
      id: 'bk1',
      name: 'Besan ke Chille',
      cuisine: 'Indian',
      prepTime: 10,
      cookTime: 15,
      protein: 14,
      cal: 280,
      highProtein: false,
      quickMake: true,
      ingredients: [
        '1 cup besan (chickpea flour)',
        '1/4 cup finely chopped onion',
        '1 green chili, minced',
        '2 tbsp fresh cilantro, chopped',
        '1/2 tsp cumin seeds',
        '1/4 tsp turmeric powder',
        '1/4 tsp Kashmiri chili powder',
        'Salt to taste',
        '3/4 cup water (adjust for pancake-batter consistency)',
        '2 tsp oil for cooking',
        'Mint chutney for serving',
      ],
      steps: [
        'Whisk besan with water until smooth with no lumps — consistency of thin pancake batter.',
        'Add onion, green chili, cilantro, cumin seeds, turmeric, chili powder, and salt. Mix well.',
        'Let batter rest 5 minutes so besan hydrates fully.',
        'Heat a non-stick skillet over medium heat. Lightly brush with oil.',
        'Pour a ladleful and spread into a thin 6-inch circle.',
        'Cook 2–3 minutes until edges lift and surface looks dry. Add a few drops of oil on top.',
        'Flip and cook 1–2 minutes more until golden spots appear.',
        'Repeat for remaining batter. Serve hot with mint chutney.',
      ],
    },
    {
      id: 'bk2',
      name: 'Overnight Oats Jar',
      cuisine: 'Quick',
      prepTime: 5,
      cookTime: 0,
      protein: 22,
      cal: 380,
      highProtein: true,
      quickMake: true,
      ingredients: [
        '1/2 cup rolled oats (old-fashioned)',
        '2/3 cup plain Greek yogurt (2%)',
        '1/3 cup milk of choice',
        '1 tbsp chia seeds',
        '1 tsp honey or maple syrup',
        '1/2 tsp vanilla extract',
        'Pinch of cinnamon',
        '1/4 cup mixed berries (fresh or frozen)',
        '1 tbsp almond butter (topping)',
      ],
      steps: [
        'Combine oats, Greek yogurt, milk, chia seeds, honey, vanilla, and cinnamon in a mason jar.',
        'Stir well to combine all ingredients.',
        'Top with berries, seal jar, refrigerate overnight (or at least 4 hours).',
        'In the morning, stir — add a splash of milk if too thick.',
        'Top with almond butter and enjoy cold.',
      ],
    },
    {
      id: 'bk3',
      name: 'Masala Oats Warm Bowl',
      cuisine: 'Indian',
      prepTime: 5,
      cookTime: 10,
      protein: 18,
      cal: 300,
      highProtein: false,
      quickMake: true,
      ingredients: [
        '1/2 cup rolled oats',
        '1 cup whole milk',
        '2 tbsp chopped onion',
        '1/4 tsp cumin seeds',
        '1/4 tsp turmeric',
        '1 green chili, minced (optional)',
        '2 tbsp mixed nuts (cashews, almonds)',
        '1 tbsp ghee or oil',
        'Salt to taste',
        'Fresh cilantro to garnish',
      ],
      steps: [
        'Heat ghee in saucepan over medium. Add cumin seeds and let splutter.',
        'Add onion and green chili, sauté 2 minutes.',
        'Add turmeric, stir 30 seconds.',
        'Add oats and toast 1 minute, stirring constantly.',
        'Pour in milk and stir. Bring to gentle simmer.',
        'Cook 5 minutes, stirring often, until oats absorb milk and thicken.',
        'Season with salt, garnish with nuts and cilantro. Serve immediately.',
      ],
    },
    {
      id: 'bk4',
      name: 'Poha with Veggies',
      cuisine: 'Indian',
      prepTime: 10,
      cookTime: 15,
      protein: 14,
      cal: 290,
      highProtein: false,
      quickMake: true,
      ingredients: [
        '1 cup thick poha (flattened rice)',
        '1/3 cup green peas (frozen)',
        '3 tbsp raw peanuts',
        '1 medium onion, finely chopped',
        '1 small potato, diced small (optional)',
        '1/4 tsp mustard seeds',
        '1/4 tsp turmeric',
        '8–10 curry leaves',
        '1 green chili, slit',
        '1 tbsp oil',
        'Salt, lemon juice, cilantro to finish',
      ],
      steps: [
        'Rinse poha in a colander under cold water for 30 seconds. Let drain 5 minutes — it should be moist but not soggy.',
        'Heat oil in a wide pan. Add mustard seeds and let pop.',
        'Add curry leaves, green chili, and peanuts. Fry 1 minute until peanuts are golden.',
        'Add onion and sauté 3 minutes until translucent. Add potato if using, cook 5 minutes.',
        'Add peas and cook 2 minutes.',
        'Add turmeric, stir well, then fold in soaked poha gently.',
        'Season with salt, cover, cook on low 2 minutes.',
        'Finish with lemon juice and cilantro. Serve warm.',
      ],
    },
    {
      id: 'bk5',
      name: 'Smoothie Bowl',
      cuisine: 'Quick',
      prepTime: 5,
      cookTime: 0,
      protein: 20,
      cal: 380,
      highProtein: true,
      quickMake: true,
      ingredients: [
        '1/2 cup frozen mixed berries',
        '1/2 cup frozen banana slices',
        '1/2 cup plain Greek yogurt (2%)',
        '2 tbsp milk (to blend)',
        '1/4 cup granola (topping)',
        '1/4 cup fresh berries (topping)',
        '1 tbsp almond butter (topping)',
        '1 tsp honey (optional)',
      ],
      steps: [
        'Blend frozen berries, frozen banana, Greek yogurt, and milk until thick and creamy.',
        'The mixture should be thicker than a drinkable smoothie — add as little liquid as possible.',
        'Pour into a bowl.',
        'Top with granola, fresh berries, and a drizzle of almond butter.',
        'Drizzle honey if desired. Eat immediately.',
      ],
    },
    {
      id: 'bk6',
      name: 'Protein Pancake Stack with Greek Yogurt',
      cuisine: 'Quick',
      prepTime: 5,
      cookTime: 15,
      protein: 30,
      cal: 340,
      highProtein: true,
      quickMake: true,
      ingredients: [
        '1/2 cup rolled oats (blended into flour)',
        '1/2 cup plain Greek yogurt (2%)',
        '1/4 cup cottage cheese',
        '1 tbsp honey',
        '1/2 tsp baking powder',
        '1/2 tsp vanilla extract',
        'Pinch of cinnamon',
        '2 tsp oil or butter for pan',
        '1/4 cup Greek yogurt for topping',
        'Fresh berries + drizzle of honey for topping',
      ],
      steps: [
        'Blend oats in a blender until they form a fine flour.',
        'Add Greek yogurt, cottage cheese, honey, baking powder, vanilla, and cinnamon to blender. Blend until smooth.',
        'Heat a non-stick pan over medium-low. Lightly oil.',
        'Pour small circles of batter (about 3 inches). Cook 2–3 minutes until bubbles form on surface.',
        'Flip and cook 1–2 more minutes. Repeat for all batter.',
        'Stack pancakes, top with Greek yogurt, fresh berries, and a drizzle of honey.',
      ],
    },
    {
      id: 'bk7',
      name: 'Masala Cottage Cheese Toast',
      cuisine: 'Quick',
      prepTime: 5,
      cookTime: 5,
      protein: 22,
      cal: 320,
      highProtein: true,
      quickMake: true,
      ingredients: [
        '2 slices sourdough bread',
        '3/4 cup cottage cheese (small curd)',
        '1/4 tsp cumin powder',
        '1/4 tsp chaat masala',
        'Pinch of Kashmiri chili powder',
        '2 tbsp cherry tomatoes, halved',
        '1 tbsp fresh cilantro, chopped',
        'Salt and black pepper to taste',
        'Drizzle of olive oil',
      ],
      steps: [
        'Toast sourdough slices until golden and crisp.',
        'In a bowl, mix cottage cheese with cumin, chaat masala, chili powder, salt, and pepper.',
        'Spread masala cottage cheese generously on each toast.',
        'Top with halved cherry tomatoes and fresh cilantro.',
        'Drizzle a little olive oil and serve immediately.',
      ],
    },
    {
      id: 'bk8',
      name: 'Oats Idli',
      cuisine: 'South Indian',
      prepTime: 10,
      cookTime: 15,
      protein: 18,
      cal: 310,
      highProtein: false,
      quickMake: false,
      ingredients: [
        '1 cup rolled oats (lightly roasted, ground coarsely)',
        '1/2 cup plain yogurt (dahi)',
        '1/4 cup rava / semolina (optional, for texture)',
        '1/2 tsp mustard seeds',
        '6–8 curry leaves',
        '1 green chili, minced',
        '1 tbsp grated carrot',
        '1 tbsp peas',
        '1/4 tsp baking soda',
        'Salt to taste',
        '1 tsp oil for tempering',
        'Peanut chutney and sambar for serving',
      ],
      steps: [
        'Lightly dry-roast oats in a pan 2 minutes. Cool and grind coarsely in a blender.',
        'Heat oil, add mustard seeds. When they pop, add curry leaves and green chili — 30 seconds.',
        'Cool the tempering, then mix with ground oats, yogurt, carrot, peas, and salt.',
        'Add baking soda and mix gently. Batter should be thick enough to scoop.',
        'Grease idli molds. Fill each mold 3/4 full.',
        'Steam for 12–15 minutes until a toothpick comes out clean.',
        'Rest 2 minutes, then unmold. Serve with peanut chutney and sambar.',
      ],
    },

    /* ── LUNCH RECIPE ──────────────────────────────────────── */
    {
      id: 'ln1',
      name: 'Quinoa Veggie Bowl (Office Lunch)',
      cuisine: 'Mediterranean',
      prepTime: 10,
      cookTime: 20,
      protein: 22,
      cal: 480,
      highProtein: true,
      quickMake: false,
      ingredients: [
        '1/2 cup dry quinoa',
        '1 cup vegetable broth (for cooking quinoa)',
        '1/2 cup canned chickpeas, rinsed',
        '1 cup assorted roasted veggies (bell peppers, zucchini, broccoli)',
        '2 tbsp crumbled feta cheese',
        '2 tbsp hummus',
        '1 tbsp olive oil',
        '1 tsp za\'atar or Italian seasoning',
        'Salt, pepper, lemon juice',
        'Fresh parsley or cilantro',
      ],
      steps: [
        'Cook quinoa in vegetable broth — bring to boil, reduce heat, simmer 15 min covered.',
        'Roast veggies: toss with olive oil, seasoning, salt. Roast at 425°F for 20 minutes.',
        'Season chickpeas with cumin, smoked paprika, and salt.',
        'Assemble bowl: quinoa base, roasted veggies, chickpeas, hummus, feta.',
        'Squeeze lemon, top with fresh herbs. Pack in container if prepping ahead.',
      ],
    },

    /* ── DINNER RECIPES ────────────────────────────────────── */
    {
      id: 'd1',
      name: 'Paneer Tikka Wrap + Raita',
      cuisine: 'Indian',
      prepTime: 15,
      cookTime: 20,
      protein: 28,
      cal: 510,
      highProtein: true,
      quickMake: false,
      ingredients: [
        '200g paneer, cut into 1-inch cubes',
        '1 bell pepper, cut into chunks',
        '1 onion, cut into chunks',
        '3 tbsp plain yogurt',
        '1 tsp tikka masala / tandoori spice blend',
        '1/2 tsp ginger paste',
        '1/2 tsp garlic paste',
        'Juice of 1/2 lemon',
        '2 large whole wheat tortillas',
        '1/4 cup raita (yogurt + cucumber + cumin + mint)',
        '1 tsp oil',
        'Salt to taste',
        'Cilantro chutney (optional)',
      ],
      steps: [
        'Marinate paneer cubes and veggies in yogurt, tikka masala, ginger, garlic, lemon, and salt for at least 30 min (or morning).',
        'Heat a grill pan or skillet on high. Brush with oil.',
        'Grill paneer and veggies in a single layer, 2–3 minutes per side until charred edges form.',
        'Make raita: mix yogurt with grated cucumber (squeezed dry), cumin, salt, and mint.',
        'Warm tortillas on the same pan 30 seconds each side.',
        'Fill each tortilla with tikka paneer and veggies, drizzle raita, roll tightly.',
        'Slice in half and serve with extra raita on the side.',
      ],
    },
    {
      id: 'd2',
      name: 'Dal Tadka + Brown Rice + Roti',
      cuisine: 'Indian',
      prepTime: 10,
      cookTime: 25,
      protein: 18,
      cal: 420,
      highProtein: false,
      quickMake: false,
      ingredients: [
        '1/2 cup toor dal (split pigeon peas)',
        '1/4 tsp turmeric',
        '1 medium tomato, chopped',
        '2 tsp ghee',
        '1/2 tsp cumin seeds',
        '1 green chili, slit',
        '4 cloves garlic, sliced',
        '1/4 tsp red chili powder',
        'Salt to taste',
        'Fresh cilantro',
        '1/2 cup brown rice (cooked separately)',
        '1 whole wheat roti',
      ],
      steps: [
        'Pressure cook toor dal with turmeric, tomato, and 1.5 cups water for 3 whistles (or simmer 25 min until very soft).',
        'Mash dal lightly with a spoon. Season with salt.',
        'Make tadka: heat ghee in a small pan until very hot. Add cumin seeds — they should sizzle immediately.',
        'Add garlic slices and fry 30 seconds until golden. Add green chili and chili powder briefly.',
        'Pour sizzling tadka over dal. Stir to combine.',
        'Garnish with cilantro. Serve with brown rice and warm roti.',
      ],
    },
    {
      id: 'd3',
      name: 'Shirataki Noodles with Tomato Lentil Marinara',
      cuisine: 'Italian',
      prepTime: 10,
      cookTime: 20,
      protein: 22,
      cal: 310,
      highProtein: true,
      quickMake: false,
      ingredients: [
        '1 pack shirataki noodles (200–250g)',
        '1/4 cup red lentils, dry',
        '1 cup crushed tomatoes (canned)',
        '1/4 cup vegetable broth',
        '3 cloves garlic, minced',
        '1/2 tsp Italian seasoning',
        '1/4 tsp red pepper flakes',
        '2 tbsp parmesan, grated',
        '1 tbsp olive oil',
        'Salt, fresh basil to finish',
      ],
      steps: [
        'Drain shirataki noodles, rinse under cold water 1 minute. Dry-fry in a hot pan 2 minutes each side — this removes the smell and improves texture.',
        'Cook lentils in broth + water for 10 minutes until just tender. Drain.',
        'In the same pan, heat olive oil. Sauté garlic 1 minute.',
        'Add crushed tomatoes, Italian seasoning, chili flakes. Simmer 10 minutes.',
        'Fold in cooked lentils. Season with salt.',
        'Toss noodles into the marinara sauce. Heat through 2 minutes.',
        'Plate and top with parmesan and fresh basil.',
      ],
    },
    {
      id: 'd4',
      name: 'Stuffed Aloo Paratha + Greek Yogurt',
      cuisine: 'Indian',
      prepTime: 20,
      cookTime: 20,
      protein: 18,
      cal: 520,
      highProtein: false,
      quickMake: false,
      ingredients: [
        '2 cups whole wheat flour (atta)',
        '2 medium potatoes, boiled and mashed',
        '1 green chili, finely minced',
        '1/2 tsp cumin powder',
        '1/4 tsp amchur (dry mango powder)',
        '2 tbsp fresh cilantro, chopped',
        'Salt to taste',
        '1 tsp ghee per paratha',
        '1/2 cup Greek yogurt (dipping)',
      ],
      steps: [
        'Make dough: mix flour with salt and enough water (~3/4 cup) to form a soft, pliable dough. Rest 15 minutes.',
        'Make filling: mash boiled potatoes with green chili, cumin, amchur, cilantro, and salt.',
        'Divide dough into 4 balls. Roll one ball into a 4-inch circle.',
        'Place 2 tbsp potato filling in center. Gather edges and pinch to seal. Flatten gently.',
        'Roll out carefully into a 6-inch paratha.',
        'Cook on hot dry griddle (tawa) 2 min, flip, spread a little ghee, cook 1 min, flip again and spread ghee.',
        'Cook until golden patches appear. Serve with cold Greek yogurt.',
      ],
    },
    {
      id: 'd5',
      name: 'Thai Peanut Shirataki Noodle Bowl',
      cuisine: 'Thai',
      prepTime: 10,
      cookTime: 10,
      protein: 20,
      cal: 350,
      highProtein: true,
      quickMake: true,
      ingredients: [
        '1 pack shirataki noodles (200g)',
        '1/2 cup shelled edamame (frozen, thawed)',
        '1/2 cucumber, julienned',
        '1/4 cup shredded purple cabbage',
        '2 green onions, sliced',
        '2 tbsp roasted peanuts, crushed',
        'Peanut Sauce: 2 tbsp almond butter, 1 tbsp low-sodium soy sauce, juice of 1 lime, 1 clove garlic minced, 1/2 tsp sesame oil, 1–2 tbsp warm water to thin',
      ],
      steps: [
        'Make peanut sauce: whisk almond butter, soy sauce, lime juice, garlic, sesame oil, and enough water to reach a pourable consistency.',
        'Drain, rinse, and dry-fry shirataki noodles 3 minutes in a hot pan until squeaky dry.',
        'Toss noodles with half the peanut sauce while still warm.',
        'Build bowl: noodles, edamame, cucumber, cabbage, green onions.',
        'Drizzle remaining sauce on top. Garnish with crushed peanuts.',
      ],
    },
    {
      id: 'd6',
      name: 'Whole Wheat Tortilla Pizza',
      cuisine: 'Italian',
      prepTime: 10,
      cookTime: 15,
      protein: 24,
      cal: 480,
      highProtein: true,
      quickMake: true,
      ingredients: [
        '2 large whole wheat tortillas',
        '100g paneer, thinly sliced or crumbled',
        '1/2 cup shredded low-fat mozzarella',
        '1/4 cup pizza sauce (Rao\'s marinara)',
        '1/2 bell pepper, thin slices',
        '4–5 mushrooms, sliced',
        '1/2 tsp Italian seasoning',
        'Red pepper flakes',
        '1 tsp olive oil',
      ],
      steps: [
        'Preheat oven to 425°F. Place tortillas on a baking sheet — brush lightly with olive oil.',
        'Spread thin layer of marinara sauce on each tortilla, leaving a 1/2 inch border.',
        'Layer with bell pepper, mushrooms, and paneer.',
        'Top with shredded mozzarella. Season with Italian seasoning and chili flakes.',
        'Bake 10–12 minutes until edges are crisp and cheese is melted and bubbly.',
        'Slice and serve immediately.',
      ],
    },
    {
      id: 'd7',
      name: 'Mediterranean Quinoa Bowl',
      cuisine: 'Mediterranean',
      prepTime: 10,
      cookTime: 20,
      protein: 20,
      cal: 430,
      highProtein: true,
      quickMake: false,
      ingredients: [
        '1/2 cup dry quinoa',
        '1/2 cup canned chickpeas, rinsed',
        '1 cup roasted veggies (eggplant, bell pepper, zucchini)',
        '2 tbsp hummus',
        '2 tbsp crumbled feta',
        '5 kalamata olives, halved',
        '1 tbsp olive oil',
        '1 tsp za\'atar',
        'Lemon juice, fresh parsley, salt',
      ],
      steps: [
        'Cook quinoa: 1/2 cup quinoa + 1 cup water + pinch salt. Boil, reduce, simmer 15 min covered.',
        'Roast veggies at 425°F with olive oil, salt, and za\'atar for 20 minutes.',
        'Season chickpeas with cumin, paprika, salt.',
        'Build bowl: quinoa base, roasted veggies, chickpeas around the sides.',
        'Add dollop of hummus in center, scatter feta and olives.',
        'Squeeze fresh lemon and scatter parsley. Drizzle remaining olive oil.',
      ],
    },
    {
      id: 'd8',
      name: 'Oats Pongal + Sambar + Peanut Chutney',
      cuisine: 'South Indian',
      prepTime: 10,
      cookTime: 20,
      protein: 16,
      cal: 350,
      highProtein: false,
      quickMake: false,
      ingredients: [
        '3/4 cup rolled oats',
        '1/4 cup yellow moong dal',
        '2 cups water',
        '1/4 tsp turmeric',
        '2 tbsp ghee',
        '1/2 tsp cumin seeds',
        '1/2 tsp black pepper, coarsely ground',
        '8–10 cashews',
        '8 curry leaves',
        '1 green chili, slit',
        'Salt to taste',
        'Sambar and peanut chutney for serving',
      ],
      steps: [
        'Cook moong dal with water and turmeric until soft (10 min). Add oats and cook 5–7 more minutes, stirring, until creamy.',
        'Season with salt. The consistency should be thick and porridge-like.',
        'Make tempering: heat ghee in small pan until very hot. Add cashews and fry 1 minute until golden.',
        'Add cumin, pepper, curry leaves, and green chili — splutter 30 seconds.',
        'Pour hot tempering over pongal. Stir in and serve immediately.',
        'Serve alongside warm sambar and peanut chutney.',
      ],
    },
    {
      id: 'd9',
      name: 'Shirataki Pad Thai with Paneer',
      cuisine: 'Thai',
      prepTime: 15,
      cookTime: 15,
      protein: 22,
      cal: 340,
      highProtein: true,
      quickMake: true,
      ingredients: [
        '1 pack shirataki noodles (200g)',
        '100g paneer, cubed',
        '1/4 cup bean sprouts (fresh)',
        '2 green onions, sliced',
        '2 tbsp roasted peanuts, crushed',
        'Pad Thai Sauce: 2 tbsp low-sodium soy sauce, 1 tbsp rice vinegar, 1 tsp sesame oil, 1 tsp honey, 1/2 tsp Sriracha (optional)',
        'Lime wedges and cilantro to serve',
        '1 tsp oil for cooking',
      ],
      steps: [
        'Drain, rinse, and dry-fry shirataki on highest heat 3 minutes until dry and slightly golden.',
        'Mix all pad thai sauce ingredients in a bowl and set aside.',
        'In a hot wok or pan, sear paneer cubes in oil until golden on all sides, 3–4 minutes. Remove.',
        'In same pan on HIGH heat, add noodles and sauce. Toss quickly 1–2 minutes.',
        'Add bean sprouts and green onions — toss 1 minute more.',
        'Return paneer to pan. Quick toss to combine.',
        'Serve immediately topped with crushed peanuts, lime, and cilantro.',
      ],
    },
    {
      id: 'd10',
      name: 'Paneer Butter Masala Lite + Brown Rice',
      cuisine: 'Indian',
      prepTime: 10,
      cookTime: 25,
      protein: 26,
      cal: 480,
      highProtein: true,
      quickMake: false,
      ingredients: [
        '200g paneer, cubed',
        '1 large onion, roughly chopped',
        '2 medium tomatoes, chopped',
        '1/2 cup plain Greek yogurt (replaces cream)',
        '2 cloves garlic',
        '1 inch ginger',
        '1 tsp garam masala',
        '1/2 tsp coriander powder',
        '1/4 tsp turmeric',
        '1/4 tsp Kashmiri chili powder',
        '1 tbsp butter or ghee',
        'Salt to taste',
        'Kasuri methi (dried fenugreek) pinch',
        '1/2 cup brown rice (cooked)',
      ],
      steps: [
        'Blend onion, tomatoes, garlic, and ginger into a smooth paste.',
        'Heat butter in pan. Add the blended paste and cook on medium, stirring often, 10 minutes until paste thickens and oil separates.',
        'Add all spices. Stir and cook 2 more minutes.',
        'Reduce heat to low. Stir in Greek yogurt gradually to prevent curdling.',
        'Add paneer cubes and 1/4 cup water. Simmer 5 minutes.',
        'Finish with a pinch of kasuri methi, crushed between palms.',
        'Serve over brown rice.',
      ],
    },
    {
      id: 'd11',
      name: 'Black Bean Veggie Burger Wrap',
      cuisine: 'Mexican',
      prepTime: 15,
      cookTime: 15,
      protein: 20,
      cal: 490,
      highProtein: true,
      quickMake: false,
      ingredients: [
        '1 can black beans, rinsed and drained',
        '1/4 cup oats or breadcrumbs',
        '2 tbsp salsa',
        '1 tsp cumin',
        '1/2 tsp smoked paprika',
        'Salt and pepper',
        '1 large whole wheat tortilla',
        '1/4 avocado, sliced',
        '2 tbsp shredded cheese (cheddar or pepper jack)',
        '2 tbsp salsa or tomatillo salsa',
        '2 tbsp Greek yogurt (sour cream sub)',
        'Shredded lettuce, jalapeño (optional)',
        '1 tsp oil for cooking',
      ],
      steps: [
        'Mash black beans roughly — keep some chunks for texture.',
        'Mix with oats, salsa, cumin, smoked paprika, salt, and pepper.',
        'Form into 2 patties. Refrigerate 10 minutes if time allows (holds better).',
        'Cook in oiled pan over medium heat, 4 minutes per side until crusted.',
        'Warm tortilla briefly in same pan.',
        'Layer: lettuce, patty, avocado slices, cheese, salsa, Greek yogurt dressing, jalapeño.',
        'Roll tightly, slice in half. Make extra patties and freeze for later.',
      ],
    },
    {
      id: 'd12',
      name: 'Besan Adai + Sambar + Peanut Chutney',
      cuisine: 'South Indian',
      prepTime: 10,
      cookTime: 20,
      protein: 18,
      cal: 290,
      highProtein: false,
      quickMake: false,
      ingredients: [
        '1 cup besan (chickpea flour)',
        '1/4 cup masoor dal or toor dal, soaked 1 hour',
        '1 onion, finely chopped',
        '2 green chilies, minced',
        '1 tbsp grated fresh coconut (optional)',
        '1/4 tsp pepper',
        '1/4 tsp cumin seeds',
        '8 curry leaves, torn',
        'Salt to taste',
        'Water to make thick batter',
        '1 tsp oil per adai',
      ],
      steps: [
        'Blend soaked dal coarsely with very little water.',
        'Mix with besan, onion, green chilies, coconut, pepper, cumin, curry leaves, and salt.',
        'Add water to make a thick, scoopable batter — thicker than chille batter.',
        'Heat a heavy tawa on medium-high. Brush with oil.',
        'Scoop batter and spread into a thick round (1/2 inch thick).',
        'Drizzle oil around edges. Cook 4 minutes until edges look dry and bottom is golden.',
        'Flip carefully and cook 3–4 more minutes.',
        'Serve with sambar and peanut chutney.',
      ],
    },
    {
      id: 'd13',
      name: 'Thai Green Curry with Paneer + Cauliflower Rice',
      cuisine: 'Thai',
      prepTime: 10,
      cookTime: 20,
      protein: 24,
      cal: 420,
      highProtein: true,
      quickMake: false,
      ingredients: [
        '200g paneer, cubed and lightly pan-fried',
        '1 cup mixed vegetables (bell pepper, zucchini, broccoli)',
        '1 can (13.5 oz) light coconut milk',
        '2 tbsp vegetarian green curry paste (Maesri brand)',
        '1 cup cauliflower rice (frozen, thawed)',
        '1 tsp coconut sugar or honey',
        '1 tbsp soy sauce',
        'Juice of 1/2 lime',
        'Fresh basil or cilantro',
        '1 tsp oil',
      ],
      steps: [
        'Heat oil in a deep pan or wok. Add green curry paste and stir-fry 1 minute until fragrant.',
        'Pour in coconut milk. Bring to a simmer.',
        'Add vegetables and simmer 8 minutes until tender.',
        'Add pan-fried paneer cubes, coconut sugar, and soy sauce.',
        'Simmer 3 more minutes. Taste and adjust salt, sweetness, lime.',
        'Meanwhile, heat cauliflower rice in microwave 3 minutes or in a pan 5 minutes.',
        'Serve curry over cauliflower rice, finish with lime juice and fresh basil.',
      ],
    },
    {
      id: 'd14',
      name: 'Dal Makhani Lite + Jeera Rice',
      cuisine: 'Indian',
      prepTime: 15,
      cookTime: 40,
      protein: 20,
      cal: 450,
      highProtein: true,
      quickMake: false,
      ingredients: [
        '1/2 cup whole black urad dal, soaked overnight',
        '2 tbsp kidney beans (rajma), soaked overnight',
        '1 cup crushed tomatoes',
        '1 tbsp butter',
        '1 tsp ginger paste',
        '1 tsp garlic paste',
        '1/2 tsp garam masala',
        '1/4 tsp red chili powder',
        '2 tbsp Greek yogurt (replaces heavy cream)',
        'Salt to taste',
        '1/2 cup basmati rice, jeera rice style',
        '1 tsp ghee + 1/2 tsp cumin seeds (for rice)',
      ],
      steps: [
        'Pressure cook soaked dal and rajma with 3 cups water and salt for 6 whistles until very soft.',
        'In a heavy pan, heat butter. Sauté ginger and garlic paste 1 minute.',
        'Add crushed tomatoes, garam masala, chili powder. Cook 10 minutes, stirring often.',
        'Add cooked dal to tomato base. Simmer on lowest heat 20 minutes, stirring occasionally.',
        'Stir in Greek yogurt off heat. Taste, adjust seasoning.',
        'Make jeera rice: wash rice, temper ghee + cumin seeds, add rice + 1 cup water, cook 15 min.',
        'Serve dal makhani over jeera rice. Tastes even better the next day.',
      ],
    },
    {
      id: 'd15',
      name: 'Shirataki Noodles with Walnut Basil Pesto',
      cuisine: 'Italian',
      prepTime: 10,
      cookTime: 10,
      protein: 18,
      cal: 340,
      highProtein: false,
      quickMake: true,
      ingredients: [
        '1 pack shirataki noodles (200g)',
        '1/2 cup fresh basil leaves (packed)',
        '3 tbsp walnuts',
        '2 tbsp parmesan, grated',
        '1 clove garlic',
        '2 tbsp olive oil',
        'Juice of 1/4 lemon',
        '1/2 cup cherry tomatoes, halved and roasted',
        'Salt, pepper',
      ],
      steps: [
        'Roast cherry tomatoes: toss with olive oil and salt, roast at 400°F for 15 minutes until blistered.',
        'Blend basil, walnuts, parmesan, garlic, olive oil, lemon, salt, and pepper until smooth pesto forms.',
        'Drain, rinse, and dry-fry shirataki noodles 3 minutes in a hot pan.',
        'Toss warm noodles with pesto immediately — the heat helps the pesto coat the noodles.',
        'Top with roasted cherry tomatoes and extra parmesan.',
      ],
    },
    {
      id: 'd16',
      name: 'Masala Dosa Filling in Whole Wheat Crepes',
      cuisine: 'South Indian',
      prepTime: 15,
      cookTime: 20,
      protein: 16,
      cal: 380,
      highProtein: false,
      quickMake: false,
      ingredients: [
        'Aloo masala: 2 boiled potatoes, 1/4 cup peas, 1/4 onion, 1/4 tsp mustard seeds, 1/4 tsp turmeric, curry leaves, green chili',
        '4 besan chille (used as crepe base): 1/2 cup besan, water to thin, salt',
        '2 tbsp oil for cooking',
        'Coconut chutney: 3 tbsp desiccated coconut, 1 green chili, 1 tsp ginger, 1/4 cup yogurt, salt, blend smooth',
        'Sambar for serving',
      ],
      steps: [
        'Make aloo masala: heat oil, add mustard seeds. When popped, add curry leaves, onion, green chili. Sauté 3 min.',
        'Add peas and turmeric. Cook 2 minutes. Add mashed potatoes and salt, mix well.',
        'Make crepe batter: thin besan + water + salt to a very thin consistency.',
        'Make thin crepes on hot oiled tawa — cook 1 min each side.',
        'Place aloo masala filling on one side of each crepe and fold.',
        'Make coconut chutney: blend all ingredients until smooth.',
        'Serve folded crepes with coconut chutney and sambar.',
      ],
    },
    {
      id: 'd17',
      name: 'Paneer Stir Fry with Soy-Ginger Sauce',
      cuisine: 'Indian',
      prepTime: 10,
      cookTime: 15,
      protein: 26,
      cal: 440,
      highProtein: true,
      quickMake: true,
      ingredients: [
        '200g paneer, cut into rectangles',
        '1 bell pepper, sliced',
        '1/2 onion, sliced',
        '4 mushrooms, sliced',
        'Sauce: 2 tbsp low-sodium soy sauce, 1 tsp sesame oil, 1 tsp honey, 1 tsp rice vinegar, 1/2 inch ginger minced, 2 cloves garlic minced, 1 tsp cornstarch + 2 tbsp water',
        '1/2 cup cooked brown rice',
        '1 tsp oil for cooking',
        'Sesame seeds, green onion to garnish',
      ],
      steps: [
        'Mix all sauce ingredients together in a small bowl. Set aside.',
        'Heat wok or pan on HIGHEST heat. Add oil.',
        'Sear paneer pieces without moving, 2 min per side until golden. Remove.',
        'In same hot pan, stir-fry onion, bell pepper, mushrooms 3–4 minutes on high heat.',
        'Pour sauce over vegetables. Stir to coat — it will thicken in 30 seconds.',
        'Return paneer to pan. Quick toss to coat everything.',
        'Serve immediately over brown rice, garnish with sesame seeds and green onion.',
      ],
    },
    {
      id: 'd18',
      name: 'Chole Chickpea Curry + Brown Rice',
      cuisine: 'Indian',
      prepTime: 10,
      cookTime: 25,
      protein: 18,
      cal: 420,
      highProtein: false,
      quickMake: false,
      ingredients: [
        '1 can (15 oz) chickpeas, rinsed well',
        '1 large onion, finely chopped',
        '2 tomatoes, pureed',
        '1 tsp ginger-garlic paste',
        '1.5 tsp chole masala (or garam masala)',
        '1/2 tsp cumin powder',
        '1/2 tsp coriander powder',
        '1/4 tsp turmeric',
        '1/4 tsp amchur',
        '1 tbsp oil',
        'Salt, fresh cilantro',
        '1/2 cup brown rice (cooked)',
      ],
      steps: [
        'Heat oil. Sauté onion 8 minutes until deep golden brown — this is key for depth.',
        'Add ginger-garlic paste, cook 1 minute.',
        'Add tomato puree and all spices. Cook 8 minutes until oil separates.',
        'Add rinsed chickpeas and 1/2 cup water. Mash a few chickpeas with the back of the spoon.',
        'Simmer 10 minutes until sauce thickens and chickpeas absorb flavors.',
        'Finish with amchur (sour kick) and fresh cilantro.',
        'Serve with brown rice.',
      ],
    },
    {
      id: 'd19',
      name: 'Oats Idli with Sambar + Peanut Chutney (Dinner)',
      cuisine: 'South Indian',
      prepTime: 10,
      cookTime: 15,
      protein: 18,
      cal: 310,
      highProtein: false,
      quickMake: false,
      ingredients: [
        '1 cup rolled oats (lightly roasted, coarsely ground)',
        '1/2 cup plain yogurt (dahi)',
        '1/4 cup rava (semolina, optional)',
        '1/2 tsp mustard seeds',
        '6 curry leaves',
        '1 green chili, minced',
        '1 tbsp grated carrot',
        '1/4 tsp baking soda',
        'Salt to taste',
        '1 tsp oil',
        'Peanut chutney + sambar for serving',
      ],
      steps: [
        'Dry roast oats 2 minutes. Cool and grind coarsely.',
        'Make tempering: heat oil, add mustard seeds, curry leaves, green chili.',
        'Cool tempering. Mix with ground oats, yogurt, carrot, salt.',
        'Add baking soda, mix gently.',
        'Fill greased idli molds 3/4 full. Steam 12–15 min until toothpick comes out clean.',
        'Rest 2 minutes before unmolding. Serve with sambar and peanut chutney.',
      ],
    },
    {
      id: 'd20',
      name: 'Thai Massaman Curry with Paneer + Cauliflower Rice',
      cuisine: 'Thai',
      prepTime: 10,
      cookTime: 20,
      protein: 22,
      cal: 430,
      highProtein: true,
      quickMake: false,
      ingredients: [
        '200g paneer, cubed',
        '1 medium potato, cubed and parboiled',
        '1 can (13.5 oz) light coconut milk',
        '2 tbsp vegetarian massaman curry paste (Maesri)',
        '1 cup cauliflower rice (frozen)',
        '1 tbsp peanuts, whole',
        '1/2 tsp coconut sugar',
        '1 tbsp soy sauce',
        'Juice of 1/2 lime',
        '1 tsp oil',
      ],
      steps: [
        'Heat oil. Stir-fry massaman paste 1 minute until fragrant.',
        'Add coconut milk and bring to simmer.',
        'Add parboiled potato and peanuts. Simmer 8 minutes.',
        'Add paneer cubes, coconut sugar, soy sauce.',
        'Simmer 5 minutes. Finish with lime juice.',
        'Heat cauliflower rice in microwave 3 min or pan 5 min.',
        'Serve massaman over cauliflower rice. Massaman is mild, creamy, and slightly sweet — great for those new to Thai food.',
      ],
    },
    {
      id: 'd21',
      name: 'Palak Paneer Lite + Roti + Brown Rice',
      cuisine: 'Indian',
      prepTime: 15,
      cookTime: 20,
      protein: 26,
      cal: 460,
      highProtein: true,
      quickMake: false,
      ingredients: [
        '200g paneer, cubed',
        '300g fresh spinach (2 large handfuls)',
        '1 onion, chopped',
        '2 tomatoes, chopped',
        '2 cloves garlic',
        '1 inch ginger',
        '1 green chili',
        '1 tsp garam masala',
        '1/4 tsp cumin seeds',
        '2 tbsp Greek yogurt',
        '1 tbsp oil or ghee',
        'Salt to taste',
        '1 roti + small portion brown rice',
      ],
      steps: [
        'Blanch spinach: boil 2 cups water, add spinach for exactly 1 minute. Immediately transfer to ice-cold water.',
        'Blend blanched spinach until very smooth and vibrant green.',
        'Heat oil, add cumin seeds. Add onion and sauté 5 minutes until golden.',
        'Add ginger-garlic paste and green chili, cook 1 minute.',
        'Add chopped tomatoes and garam masala. Cook 8 minutes.',
        'Add blended spinach puree. Simmer 5 minutes.',
        'Stir in Greek yogurt (off heat first, then return to low heat).',
        'Add paneer cubes. Simmer 3 minutes. Serve with roti and small portion brown rice.',
      ],
    },
    {
      id: 'd22',
      name: 'Chole Stuffed Whole Wheat Quesadilla',
      cuisine: 'Mexican',
      prepTime: 10,
      cookTime: 10,
      protein: 24,
      cal: 450,
      highProtein: true,
      quickMake: true,
      ingredients: [
        '2 large whole wheat tortillas',
        '1/2 cup canned chickpeas, lightly spiced with cumin + coriander',
        '1/4 cup shredded mozzarella or cheddar',
        '2 tbsp Greek yogurt dip (mix yogurt + pinch cumin + salt)',
        'Cilantro, salsa, jalapeño to serve',
        '1 tsp oil',
      ],
      steps: [
        'Season chickpeas: warm in pan with cumin, coriander, salt, smoked paprika. Lightly smash half.',
        'Heat a wide pan over medium. Brush with oil.',
        'Lay one tortilla flat. Scatter spiced chickpeas and cheese on one half.',
        'Fold over to form a half-moon. Press down with spatula.',
        'Cook 3 minutes per side, pressing firmly each time, until golden and crispy.',
        'Cut into wedges. Serve with Greek yogurt dip, salsa, and cilantro.',
      ],
    },
    {
      id: 'd23',
      name: 'Shirataki Noodles with Roasted Garlic Yogurt Cream Sauce',
      cuisine: 'Italian',
      prepTime: 10,
      cookTime: 20,
      protein: 24,
      cal: 370,
      highProtein: true,
      quickMake: false,
      ingredients: [
        '1 pack shirataki noodles (200g)',
        '100g paneer, cubed',
        '1 cup baby spinach',
        '4 cloves garlic (roasted: drizzle with oil, wrap in foil, bake 30 min at 400°F)',
        '1/2 cup plain Greek yogurt',
        '2 tbsp parmesan',
        '2 tbsp pasta water or vegetable broth',
        'Salt, pepper, pinch of nutmeg',
      ],
      steps: [
        'Roast garlic ahead of time (400°F, 30 min in foil — can do this any time and refrigerate).',
        'Drain, rinse, dry-fry shirataki noodles 3 minutes on high heat.',
        'Sear paneer cubes in a little oil until golden. Remove.',
        'In the same pan on low heat, squeeze roasted garlic from skins. Mash into a paste.',
        'Off heat, stir in Greek yogurt, parmesan, pasta water, salt, pepper, and nutmeg.',
        'Return pan to LOW heat — gently warm sauce (never boil or yogurt will break).',
        'Add spinach and wilt. Toss in noodles and paneer. Serve immediately.',
      ],
    },
    {
      id: 'd24',
      name: 'South Indian Tomato Rice + Raita + Papad',
      cuisine: 'South Indian',
      prepTime: 10,
      cookTime: 20,
      protein: 16,
      cal: 360,
      highProtein: false,
      quickMake: true,
      ingredients: [
        '1/2 cup basmati rice (cooked)',
        '2 medium tomatoes, pureed',
        '1 onion, sliced thin',
        '1/2 tsp mustard seeds',
        '1/4 tsp urad dal',
        '8 curry leaves',
        '1 green chili, slit',
        '1/4 tsp turmeric',
        '1/4 tsp red chili powder',
        '1 tbsp oil',
        'Salt to taste',
        'Cucumber raita + papad for serving',
      ],
      steps: [
        'Cook rice and spread on a plate to cool and separate grains.',
        'Heat oil. Add mustard seeds and let pop. Add urad dal and fry 30 seconds.',
        'Add curry leaves, onion, and green chili. Sauté 5 minutes until onion softens.',
        'Add tomato puree, turmeric, chili powder, and salt. Cook 8–10 minutes until very thick.',
        'Fold in cooked rice gently. Mix until every grain is coated. Cook 2 more minutes.',
        'Serve with cucumber raita and roasted/microwave-crisp papad.',
      ],
    },
    {
      id: 'd25',
      name: 'Shirataki Noodles with Avocado Pesto + Cherry Tomatoes + Feta',
      cuisine: 'Italian',
      prepTime: 10,
      cookTime: 5,
      protein: 16,
      cal: 340,
      highProtein: false,
      quickMake: true,
      ingredients: [
        '1 pack shirataki noodles (200g)',
        '1/2 ripe avocado',
        '1/4 cup fresh basil leaves',
        'Juice of 1/2 lemon',
        '1 clove garlic',
        '2 tbsp parmesan',
        '1 tbsp olive oil',
        '1/2 cup cherry tomatoes, halved',
        '2 tbsp crumbled feta',
        'Salt, pepper, red pepper flakes',
      ],
      steps: [
        'Blend avocado, basil, lemon juice, garlic, parmesan, and olive oil until smooth. Season with salt and pepper.',
        'Drain, rinse, and dry-fry shirataki noodles 3 minutes in a hot pan.',
        'Remove pan from heat. Toss noodles with avocado pesto while still warm.',
        'Top with cherry tomatoes, crumbled feta, and red pepper flakes.',
        'Serve immediately — avocado pesto is best fresh (browns quickly).',
      ],
    },
  ];

})();
