/* =============================================================
   data.js — April 2025 meal data + recipe library
   My Wellness Journey
   ============================================================= */

(function () {
  'use strict';

  /* ── Helpers ─────────────────────────────────────────────── */
  const PS = { type: 'Protein Shake', food: 'Premier Protein Café Latte', protein: 30, cal: 160 };

  function day(date, dayNum, dow, short, week, isOffice, isWFH, isWeekend, hasOT, otTime, meals) {
    return { date, dayNum, dow, short, week, isOffice, isWFH, isWeekend, hasOT, otTime, meals };
  }

  /* ── Breakfast lookup ───────────────────────────────────── */
  const BK = {
    besanChille:    { type: 'Breakfast', food: 'Besan ke chille + mint chutney',               protein: 14, cal: 220 },
    oatsJar:        { type: 'Breakfast', food: 'Overnight oats jar',                            protein: 22, cal: 380 },
    masalaOats:     { type: 'Breakfast', food: 'Masala oats + milk + nuts',                     protein: 14, cal: 310 },
    poha:           { type: 'Breakfast', food: 'Poha with peas + peanuts',                      protein: 10, cal: 280 },
    smoothieBowl:   { type: 'Breakfast', food: 'Smoothie bowl — yogurt + berries + granola',    protein: 20, cal: 360 },
  };

  // week1 Mon/Wed/Fri/Sun → besanChille, Tue/Thu/Sat → oatsJar
  // week2 Mon/Wed/Fri/Sun → oatsJar,    Tue/Thu/Sat → masalaOats
  // week3 Mon/Wed/Fri/Sun → poha,       Tue/Thu/Sat → besanChille
  // week4 Mon/Wed/Fri/Sun → smoothieBowl, Tue/Thu/Sat → oatsJar
  function breakfast(week, dow) {
    const mwfs = ['Mon','Wed','Fri','Sun'].includes(dow);
    if (week === 1) return mwfs ? BK.besanChille  : BK.oatsJar;
    if (week === 2) return mwfs ? BK.oatsJar      : BK.masalaOats;
    if (week === 3) return mwfs ? BK.poha          : BK.besanChille;
    return mwfs ? BK.smoothieBowl : BK.oatsJar;
  }

  /* ── Lunch lookup ───────────────────────────────────────── */
  function lunch(isOffice, isWFH, dow, isWeekend) {
    if (isOffice) return { type: 'Lunch', food: 'Quinoa veggie bowl — roasted veggies, chickpeas, feta', protein: 22, cal: 480 };
    if (isWFH && dow === 'Mon') return { type: 'Lunch', food: 'Leftover dinner or lentil soup + roti',    protein: 18, cal: 360 };
    if (isWFH && dow === 'Fri') return { type: 'Lunch', food: 'Leftover dinner or dal + brown rice',      protein: 18, cal: 360 };
    return { type: 'Lunch', food: 'Light wrap or leftovers', protein: 15, cal: 320 };
  }

  /* ── Snack lookup ───────────────────────────────────────── */
  function snack(isOffice, week, isWFH, isWeekend) {
    if (isOffice && (week === 1 || week === 3)) return { type: 'Snack', food: 'Cottage cheese + cucumber packed',  protein: 14, cal: 140 };
    if (isOffice && (week === 2 || week === 4)) return { type: 'Snack', food: 'Hummus + veggie sticks packed',     protein: 5,  cal: 140 };
    if (isWFH)    return { type: 'Snack', food: 'Apple + almond butter',           protein: 7,  cal: 200 };
    return { type: 'Snack', food: 'Greek yogurt + mixed berries',        protein: 18, cal: 200 };
  }

  /* ── Dinners ────────────────────────────────────────────── */
  const DINNERS = {
    1:  { type: 'Dinner', food: 'Dal tadka + brown rice + roti',                                       protein: 18, cal: 420 },
    2:  { type: 'Dinner', food: 'Shirataki noodles with marinara + paneer meatballs',                  protein: 24, cal: 310 },
    3:  { type: 'Dinner', food: 'Stuffed aloo paratha + Greek yogurt',                                 protein: 18, cal: 520 },
    4:  { type: 'Dinner', food: 'Paneer tikka wrap + raita',                                           protein: 28, cal: 510 },
    5:  { type: 'Dinner', food: 'Thai peanut tofu bowl with shirataki noodles + peanut sauce',         protein: 20, cal: 390 },
    6:  { type: 'Dinner', food: 'Warm quinoa grain bowl with roasted veggies + feta',                  protein: 20, cal: 430 },
    7:  { type: 'Dinner', food: 'South Indian oats pongal + sambar + peanut chutney',                  protein: 16, cal: 350 },
    8:  { type: 'Dinner', food: 'Shirataki pad thai — tofu, peanuts, bean sprouts, lime',              protein: 18, cal: 320 },
    9:  { type: 'Dinner', food: 'Paneer butter masala lite + brown rice',                              protein: 26, cal: 480 },
    10: { type: 'Dinner', food: 'Black bean veggie burger wrap',                                       protein: 20, cal: 490 },
    11: { type: 'Dinner', food: 'Rava upma + coconut chutney + paneer scramble',                       protein: 20, cal: 380 },
    12: { type: 'Dinner', food: 'Italian shirataki noodles with tomato-lentil sauce + parmesan',       protein: 22, cal: 380 },
    13: { type: 'Dinner', food: 'Besan adai + sambar + peanut chutney',                                protein: 18, cal: 290 },
    14: { type: 'Dinner', food: 'Thai green curry with paneer + veggies over cauliflower rice',        protein: 24, cal: 420 },
    15: { type: 'Dinner', food: 'Dal makhani lite + jeera rice',                                       protein: 20, cal: 450 },
    16: { type: 'Dinner', food: 'Shirataki noodles with pesto + roasted cherry tomatoes',              protein: 18, cal: 340 },
    17: { type: 'Dinner', food: 'Masala dosa filling in whole wheat crepes + coconut chutney',         protein: 16, cal: 380 },
    18: { type: 'Dinner', food: 'Paneer stir fry with bell peppers + soy-ginger sauce over brown rice',protein: 26, cal: 440 },
    19: { type: 'Dinner', food: 'Thai basil fried cauliflower rice with paneer + vegetables',          protein: 22, cal: 380 },
    20: { type: 'Dinner', food: 'Mediterranean quinoa bowl — chickpeas, roasted veggies, hummus, feta',protein: 20, cal: 430 },
    21: { type: 'Dinner', food: 'South Indian tomato rice + raita + papad',                            protein: 16, cal: 360 },
    22: { type: 'Dinner', food: 'Shirataki noodles — roasted garlic cream sauce + spinach + paneer',   protein: 24, cal: 370 },
    23: { type: 'Dinner', food: 'Chole chickpea curry + brown rice',                                   protein: 18, cal: 420 },
    24: { type: 'Dinner', food: 'Cottage cheese + veggie stuffed whole wheat quesadilla',              protein: 24, cal: 450 },
    25: { type: 'Dinner', food: 'Oats idli + sambar + peanut chutney',                                 protein: 18, cal: 310 },
    26: { type: 'Dinner', food: 'Thai massaman curry with paneer + potatoes over cauliflower rice',    protein: 22, cal: 430 },
    27: { type: 'Dinner', food: 'Whole wheat pizza — paneer, bell peppers, mushrooms, low-fat mozzarella', protein: 24, cal: 480 },
    28: { type: 'Dinner', food: 'South Indian lemon rice + cucumber raita',                            protein: 14, cal: 340 },
    29: { type: 'Dinner', food: 'Shirataki noodles with avocado pesto + cherry tomatoes',              protein: 16, cal: 350 },
    30: { type: 'Dinner', food: 'Palak paneer lite + roti + brown rice',                               protein: 26, cal: 460 },
  };

  /* ── April 2025 schedule ────────────────────────────────── */
  // dow: Tue=2, Wed=3, Thu=4, Fri=5, Sat=6, Sun=0, Mon=1
  // Office: Tue/Wed/Thu, WFH: Mon/Fri, Weekend: Sat/Sun
  // OT: Mon/Fri=7:30am, Tue/Wed/Thu=4:30pm, Sat/Sun=none
  const APRIL_DAYS_META = [
    // date        dayNum dow   short       week office wfh  wknd  ot    otTime
    ['2025-04-01',  1, 'Tue', 'Apr 1',  1, true,  false, false, true,  '4:30pm'],
    ['2025-04-02',  2, 'Wed', 'Apr 2',  1, true,  false, false, true,  '4:30pm'],
    ['2025-04-03',  3, 'Thu', 'Apr 3',  1, true,  false, false, true,  '4:30pm'],
    ['2025-04-04',  4, 'Fri', 'Apr 4',  1, false, true,  false, true,  '7:30am'],
    ['2025-04-05',  5, 'Sat', 'Apr 5',  1, false, false, true,  false, null],
    ['2025-04-06',  6, 'Sun', 'Apr 6',  1, false, false, true,  false, null],
    ['2025-04-07',  7, 'Mon', 'Apr 7',  2, false, true,  false, true,  '7:30am'],
    ['2025-04-08',  8, 'Tue', 'Apr 8',  2, true,  false, false, true,  '4:30pm'],
    ['2025-04-09',  9, 'Wed', 'Apr 9',  2, true,  false, false, true,  '4:30pm'],
    ['2025-04-10', 10, 'Thu', 'Apr 10', 2, true,  false, false, true,  '4:30pm'],
    ['2025-04-11', 11, 'Fri', 'Apr 11', 2, false, true,  false, true,  '7:30am'],
    ['2025-04-12', 12, 'Sat', 'Apr 12', 2, false, false, true,  false, null],
    ['2025-04-13', 13, 'Sun', 'Apr 13', 2, false, false, true,  false, null],
    ['2025-04-14', 14, 'Mon', 'Apr 14', 3, false, true,  false, true,  '7:30am'],
    ['2025-04-15', 15, 'Tue', 'Apr 15', 3, true,  false, false, true,  '4:30pm'],
    ['2025-04-16', 16, 'Wed', 'Apr 16', 3, true,  false, false, true,  '4:30pm'],
    ['2025-04-17', 17, 'Thu', 'Apr 17', 3, true,  false, false, true,  '4:30pm'],
    ['2025-04-18', 18, 'Fri', 'Apr 18', 3, false, true,  false, true,  '7:30am'],
    ['2025-04-19', 19, 'Sat', 'Apr 19', 3, false, false, true,  false, null],
    ['2025-04-20', 20, 'Sun', 'Apr 20', 3, false, false, true,  false, null],
    ['2025-04-21', 21, 'Mon', 'Apr 21', 4, false, true,  false, true,  '7:30am'],
    ['2025-04-22', 22, 'Tue', 'Apr 22', 4, true,  false, false, true,  '4:30pm'],
    ['2025-04-23', 23, 'Wed', 'Apr 23', 4, true,  false, false, true,  '4:30pm'],
    ['2025-04-24', 24, 'Thu', 'Apr 24', 4, true,  false, false, true,  '4:30pm'],
    ['2025-04-25', 25, 'Fri', 'Apr 25', 4, false, true,  false, true,  '7:30am'],
    ['2025-04-26', 26, 'Sat', 'Apr 26', 4, false, false, true,  false, null],
    ['2025-04-27', 27, 'Sun', 'Apr 27', 4, false, false, true,  false, null],
    ['2025-04-28', 28, 'Mon', 'Apr 28', 4, false, true,  false, true,  '7:30am'],
    ['2025-04-29', 29, 'Tue', 'Apr 29', 4, true,  false, false, true,  '4:30pm'],
    ['2025-04-30', 30, 'Wed', 'Apr 30', 4, true,  false, false, true,  '4:30pm'],
  ];

  const APRIL_DAYS = APRIL_DAYS_META.map(([date, dayNum, dow, short, week, isOffice, isWFH, isWeekend, hasOT, otTime]) => {
    const bk = breakfast(week, dow);
    const ln = lunch(isOffice, isWFH, dow, isWeekend);
    const sn = snack(isOffice, week, isWFH, isWeekend);
    const dn = DINNERS[dayNum];
    return {
      date, dayNum, dow, short, week,
      isOffice, isWFH, isWeekend, hasOT, otTime,
      meals: [bk, PS, ln, sn, dn],
    };
  });

  window.APRIL_DATA = { days: APRIL_DAYS };

  /* ═══════════════════════════════════════════════════════════
     RECIPES
  ═══════════════════════════════════════════════════════════ */
  window.RECIPES = [
    {
      id: 1,
      name: 'Besan ke Chille',
      cuisine: 'Indian',
      prepTime: 10,
      cookTime: 15,
      protein: 14,
      cal: 220,
      highProtein: false,
      quickMake: true,
      ingredients: [
        '1 cup besan (chickpea flour)',
        '1/4 cup finely chopped onion',
        '1 green chili, minced',
        '2 tbsp fresh cilantro, chopped',
        '1/2 tsp cumin seeds',
        '1/4 tsp turmeric powder',
        '1/4 tsp red chili powder',
        'Salt to taste',
        'Water to make batter (about 3/4 cup)',
        '2 tsp oil for cooking',
        'Mint chutney for serving',
      ],
      steps: [
        'Whisk besan with water until smooth batter forms — consistency of pancake batter.',
        'Add onion, green chili, cilantro, cumin seeds, turmeric, chili powder, and salt. Mix well.',
        'Let batter rest 5 minutes.',
        'Heat a non-stick skillet over medium heat. Lightly brush with oil.',
        'Pour a ladleful of batter and spread into a thin circle (about 6 inches).',
        'Cook 2–3 minutes until edges lift and top looks set. Drizzle a few drops of oil on top.',
        'Flip and cook 1–2 minutes more until golden.',
        'Repeat for remaining batter. Serve hot with mint chutney.',
      ],
    },
    {
      id: 2,
      name: 'Overnight Oats Jar',
      cuisine: 'Quick',
      prepTime: 5,
      cookTime: 0,
      protein: 22,
      cal: 380,
      highProtein: true,
      quickMake: true,
      ingredients: [
        '1/2 cup rolled oats',
        '2/3 cup plain Greek yogurt (2%)',
        '1/3 cup milk of choice',
        '1 tbsp chia seeds',
        '1 tsp honey or maple syrup',
        '1/2 tsp vanilla extract',
        '1/4 cup mixed berries (fresh or frozen)',
        '1 tbsp almond butter (optional topping)',
        'Pinch of cinnamon',
      ],
      steps: [
        'Combine oats, Greek yogurt, milk, chia seeds, honey, vanilla, and cinnamon in a mason jar.',
        'Stir well to combine all ingredients.',
        'Top with berries.',
        'Seal the jar and refrigerate overnight (or at least 4 hours).',
        'In the morning, stir the oats — add a splash of milk if too thick.',
        'Top with almond butter if desired and enjoy cold.',
      ],
    },
    {
      id: 3,
      name: 'Masala Oats',
      cuisine: 'Indian',
      prepTime: 5,
      cookTime: 10,
      protein: 14,
      cal: 310,
      highProtein: false,
      quickMake: true,
      ingredients: [
        '1/2 cup rolled oats',
        '1 cup whole milk',
        '1/4 cup mixed nuts (cashews, almonds)',
        '1/4 tsp cumin seeds',
        '1/4 tsp turmeric',
        '1 green chili, minced (optional)',
        '2 tbsp chopped onion',
        '1 tbsp ghee or oil',
        'Salt to taste',
        'Fresh cilantro to garnish',
      ],
      steps: [
        'Heat ghee in a saucepan over medium heat. Add cumin seeds and let them splutter.',
        'Add onion and green chili. Sauté 2 minutes until soft.',
        'Add turmeric and stir for 30 seconds.',
        'Add oats and toast 1 minute, stirring constantly.',
        'Pour in milk and stir. Bring to a gentle simmer.',
        'Cook 5 minutes, stirring often, until oats absorb milk and thicken.',
        'Season with salt, garnish with nuts and cilantro.',
      ],
    },
    {
      id: 4,
      name: 'Poha with Peas & Peanuts',
      cuisine: 'Indian',
      prepTime: 10,
      cookTime: 15,
      protein: 10,
      cal: 280,
      highProtein: false,
      quickMake: true,
      ingredients: [
        '1 cup thick poha (flattened rice)',
        '1/3 cup green peas (fresh or frozen)',
        '3 tbsp raw peanuts',
        '1 medium onion, finely chopped',
        '1 green chili, minced',
        '1/2 tsp mustard seeds',
        '8–10 curry leaves',
        '1/4 tsp turmeric',
        '1 tsp lemon juice',
        '1 tbsp oil',
        'Salt to taste, cilantro to garnish',
      ],
      steps: [
        'Rinse poha in a colander under cold water until soft but not mushy. Drain well.',
        'Dry roast peanuts in a pan over medium heat until golden. Set aside.',
        'Heat oil in the same pan. Add mustard seeds — let them pop.',
        'Add curry leaves, green chili, and onion. Sauté until onion turns translucent.',
        'Add peas and turmeric. Cook 3 minutes until peas are tender.',
        'Add softened poha and peanuts. Gently toss to combine.',
        'Season with salt. Cook 2 minutes, stirring gently.',
        'Squeeze lemon juice, garnish with cilantro. Serve warm.',
      ],
    },
    {
      id: 5,
      name: 'Smoothie Bowl',
      cuisine: 'Quick',
      prepTime: 8,
      cookTime: 0,
      protein: 20,
      cal: 360,
      highProtein: true,
      quickMake: true,
      ingredients: [
        '3/4 cup plain Greek yogurt',
        '1/2 frozen banana',
        '1/2 cup frozen mixed berries',
        '2 tbsp granola',
        '1/4 cup fresh berries for topping',
        '1 tbsp honey',
        '1 tbsp chia seeds',
        '2 tbsp milk (to blend)',
        'Sliced almonds for topping',
      ],
      steps: [
        'Blend Greek yogurt, frozen banana, frozen berries, and milk until thick and smooth.',
        'The mixture should be thicker than a drinkable smoothie — add less milk for thicker result.',
        'Pour into a bowl.',
        'Top with granola, fresh berries, chia seeds, sliced almonds, and a drizzle of honey.',
        'Serve immediately — eat before the granola softens for best texture.',
      ],
    },
    {
      id: 6,
      name: 'Quinoa Veggie Bowl',
      cuisine: 'Quick',
      prepTime: 10,
      cookTime: 20,
      protein: 22,
      cal: 480,
      highProtein: true,
      quickMake: false,
      ingredients: [
        '1/2 cup dry quinoa, rinsed',
        '1 cup vegetable broth',
        '1/2 cup canned chickpeas, drained and rinsed',
        '1 zucchini, diced',
        '1 bell pepper, diced',
        '1/2 cup cherry tomatoes, halved',
        '3 tbsp crumbled feta',
        '2 tsp olive oil',
        '1/2 tsp smoked paprika',
        'Salt and pepper to taste',
        'Fresh lemon juice + parsley to serve',
      ],
      steps: [
        'Cook quinoa in vegetable broth per package directions (about 15 minutes). Fluff with fork.',
        'Preheat oven to 400°F. Toss zucchini and bell pepper with olive oil, paprika, salt, and pepper.',
        'Roast vegetables 18–20 minutes until tender and slightly caramelized.',
        'Meanwhile, lightly pan-fry chickpeas in a dry skillet with a pinch of paprika and salt until crispy.',
        'Assemble bowl: quinoa base, roasted veggies, chickpeas, cherry tomatoes, feta.',
        'Drizzle with lemon juice and garnish with parsley. Pack in a jar for office days.',
      ],
    },
    {
      id: 7,
      name: 'Dal Tadka',
      cuisine: 'Indian',
      prepTime: 10,
      cookTime: 30,
      protein: 18,
      cal: 420,
      highProtein: false,
      quickMake: false,
      ingredients: [
        '1 cup toor dal (split pigeon peas), rinsed',
        '3 cups water',
        '1 medium tomato, chopped',
        '1/2 tsp turmeric',
        '2 tsp ghee',
        '1/2 tsp cumin seeds',
        '1/4 tsp hing (asafoetida)',
        '3 garlic cloves, minced',
        '1/2 tsp garam masala',
        '1/2 tsp Kashmiri chili powder',
        'Salt to taste, cilantro to garnish',
      ],
      steps: [
        'Pressure cook or boil dal with water, tomato, and turmeric until completely soft (20 mins).',
        'Mash dal gently to desired consistency. Add water if too thick.',
        'For tadka: heat ghee in a small pan over high heat until shimmering.',
        'Add cumin seeds and hing — they should sizzle immediately.',
        'Add garlic and cook 30 seconds until golden (do not burn).',
        'Add chili powder — stir 10 seconds, then pour tadka over dal.',
        'Stir in garam masala and salt. Simmer 5 minutes.',
        'Garnish with cilantro. Serve with brown rice and roti.',
      ],
    },
    {
      id: 8,
      name: 'Shirataki Paneer Meatball Marinara',
      cuisine: 'Italian',
      prepTime: 20,
      cookTime: 25,
      protein: 24,
      cal: 310,
      highProtein: true,
      quickMake: false,
      ingredients: [
        '2 packs shirataki noodles, rinsed and dry-toasted',
        '200g paneer, grated',
        '1 egg or 2 tbsp aquafaba (vegan binder)',
        '2 tbsp besan (chickpea flour)',
        '1 tsp Italian seasoning',
        '1/2 tsp garlic powder',
        '1/2 cup Rao\'s Homemade marinara sauce',
        '1 can (14 oz) crushed tomatoes',
        '2 garlic cloves, minced',
        '1 tsp olive oil',
        'Fresh basil, salt and pepper',
      ],
      steps: [
        'Mix grated paneer, egg/aquafaba, besan, Italian seasoning, garlic powder, salt, and pepper.',
        'Roll into 10–12 small meatballs. Pan-fry in a lightly oiled skillet until golden all over.',
        'In a separate pan, sauté garlic in olive oil 1 minute. Add crushed tomatoes and marinara sauce.',
        'Simmer sauce 10 minutes. Season with salt, pepper, and basil.',
        'Add paneer meatballs to sauce. Simmer together 5 minutes.',
        'Dry-toast shirataki noodles in a dry pan 5 minutes to remove water.',
        'Serve noodles topped with sauce and paneer meatballs. Garnish with fresh basil.',
      ],
    },
    {
      id: 9,
      name: 'Stuffed Aloo Paratha',
      cuisine: 'Indian',
      prepTime: 20,
      cookTime: 20,
      protein: 18,
      cal: 520,
      highProtein: false,
      quickMake: false,
      ingredients: [
        '2 cups whole wheat flour (atta)',
        '2 medium potatoes, boiled and mashed',
        '1 green chili, finely minced',
        '1/2 tsp cumin seeds',
        '1/4 tsp amchur (dry mango powder)',
        '1/4 tsp garam masala',
        '2 tbsp fresh cilantro, chopped',
        '1 tbsp ghee per paratha',
        'Salt to taste',
        '1/2 cup plain Greek yogurt for serving',
      ],
      steps: [
        'Make dough: mix flour with water and a pinch of salt. Knead 5 minutes to smooth. Rest 15 mins.',
        'Mix mashed potato with chili, cumin, amchur, garam masala, cilantro, and salt.',
        'Divide dough into 4 balls. Roll each into a 5-inch circle.',
        'Place a portion of filling in center, fold edges up and seal. Gently re-roll into 7-inch circle.',
        'Cook on a hot dry tawa (griddle) 2 minutes each side until light brown spots form.',
        'Apply ghee generously on both sides. Cook 1 more minute per side until crispy and golden.',
        'Serve hot with cold Greek yogurt and pickle.',
      ],
    },
    {
      id: 10,
      name: 'Paneer Tikka Wrap',
      cuisine: 'Indian',
      prepTime: 15,
      cookTime: 20,
      protein: 28,
      cal: 510,
      highProtein: true,
      quickMake: false,
      ingredients: [
        '250g paneer, cut into 1-inch cubes',
        '1/2 cup plain yogurt',
        '1 tsp tikka masala spice mix',
        '1/2 tsp turmeric',
        '1/2 tsp kashmiri chili powder',
        '1 tsp ginger-garlic paste',
        '2 large whole wheat tortillas',
        '1/4 cup mint-coriander chutney',
        '1/2 cup raita (yogurt + cucumber + cumin)',
        '1 cup shredded cabbage + onion mix',
        'Lemon juice, salt to taste',
      ],
      steps: [
        'Marinate paneer cubes in yogurt, tikka masala, turmeric, chili powder, ginger-garlic paste, and salt for at least 15 minutes (overnight is better).',
        'Thread onto skewers and grill on a grill pan over high heat, 3–4 minutes per side until charred.',
        'Alternatively, bake at 450°F for 15 minutes, then broil 3 minutes.',
        'Make raita: mix yogurt with grated cucumber, roasted cumin, salt, and mint.',
        'Warm tortillas on a dry pan.',
        'Spread chutney on tortilla, add cabbage mix, tikka paneer, and a drizzle of raita.',
        'Roll tightly, cut diagonally, and serve.',
      ],
    },
    {
      id: 11,
      name: 'Thai Peanut Tofu Bowl',
      cuisine: 'Thai',
      prepTime: 15,
      cookTime: 20,
      protein: 20,
      cal: 390,
      highProtein: true,
      quickMake: false,
      ingredients: [
        '2 packs shirataki noodles, rinsed and dry-toasted',
        '200g extra-firm tofu, pressed and cubed',
        '3 tbsp natural peanut butter',
        '2 tbsp soy sauce or tamari',
        '1 tbsp rice vinegar',
        '1 tsp sesame oil',
        '1 tsp chili garlic sauce',
        '1 tsp honey',
        '1 lime, juiced',
        '1 cup shredded red cabbage',
        '2 green onions, sliced',
        'Crushed peanuts, cilantro to serve',
      ],
      steps: [
        'Press tofu for 15 minutes. Cut into cubes. Pan-fry in a lightly oiled skillet until golden on all sides.',
        'Whisk peanut butter, soy sauce, rice vinegar, sesame oil, chili garlic sauce, honey, and lime juice together. Add 2–3 tbsp warm water to thin.',
        'Dry-toast shirataki noodles in a dry pan over high heat 5 minutes, tossing frequently.',
        'Toss noodles and tofu with peanut sauce. Heat through 2 minutes.',
        'Serve in bowls topped with red cabbage, green onions, crushed peanuts, and cilantro.',
        'Squeeze extra lime juice before eating.',
      ],
    },
    {
      id: 12,
      name: 'South Indian Oats Pongal',
      cuisine: 'South Indian',
      prepTime: 10,
      cookTime: 20,
      protein: 16,
      cal: 350,
      highProtein: false,
      quickMake: false,
      ingredients: [
        '1 cup rolled oats',
        '1/4 cup moong dal (split yellow lentils)',
        '2 cups water',
        '1 cup milk',
        '1/2 tsp black pepper, coarsely ground',
        '1 tsp cumin seeds',
        '8–10 curry leaves',
        '2 tbsp ghee',
        '2 tbsp raw cashews',
        '1/4 tsp turmeric',
        'Ginger, 1-inch piece, grated',
        'Salt to taste',
      ],
      steps: [
        'Dry roast moong dal 3 minutes until fragrant. Rinse and set aside.',
        'Cook dal with 1 cup water until soft. In another pot, cook oats with milk and remaining water.',
        'Combine cooked dal and oats. Stir well, add turmeric and salt.',
        'Simmer together 5 minutes, stirring to prevent sticking.',
        'For tadka: heat ghee in a small pan. Fry cashews until golden — remove and set aside.',
        'Add cumin seeds, curry leaves, grated ginger, and black pepper to the same ghee. Sizzle 30 seconds.',
        'Pour tadka over oats pongal. Top with fried cashews.',
        'Serve hot with sambar and peanut chutney.',
      ],
    },
    {
      id: 13,
      name: 'Shirataki Pad Thai',
      cuisine: 'Thai',
      prepTime: 15,
      cookTime: 15,
      protein: 18,
      cal: 320,
      highProtein: false,
      quickMake: true,
      ingredients: [
        '2 packs shirataki noodles, rinsed and dry-toasted',
        '150g extra-firm tofu, crumbled',
        '2 tbsp soy sauce or tamari',
        '1 tbsp fish sauce substitute (or coconut aminos)',
        '1 tbsp rice vinegar',
        '2 tsp sugar or honey',
        '1 cup bean sprouts',
        '3 green onions, sliced',
        '2 tbsp crushed peanuts',
        '1 lime, cut into wedges',
        '1 tbsp oil',
        '2 garlic cloves, minced',
      ],
      steps: [
        'Whisk soy sauce, fish sauce substitute, rice vinegar, and sugar into a sauce.',
        'Dry-toast shirataki noodles in a dry skillet over high heat until squeaky and dry.',
        'Heat oil in a wok over high heat. Add garlic and stir-fry 30 seconds.',
        'Add crumbled tofu. Stir-fry 3 minutes until lightly golden.',
        'Add shirataki noodles and sauce. Toss everything together over high heat 2 minutes.',
        'Add bean sprouts, toss 1 minute (keep crunchy).',
        'Serve garnished with green onions, peanuts, and lime wedges.',
      ],
    },
    {
      id: 14,
      name: 'Paneer Butter Masala Lite',
      cuisine: 'Indian',
      prepTime: 15,
      cookTime: 25,
      protein: 26,
      cal: 480,
      highProtein: true,
      quickMake: false,
      ingredients: [
        '250g paneer, cubed',
        '2 medium tomatoes, pureed',
        '1 medium onion, finely chopped',
        '2 garlic cloves, minced',
        '1-inch ginger, grated',
        '1/2 cup plain Greek yogurt (replaces cream)',
        '1 tbsp butter or ghee',
        '1 tsp kashmiri chili powder',
        '1 tsp coriander powder',
        '1/2 tsp garam masala',
        '1/2 tsp honey',
        'Salt, kasuri methi (dried fenugreek) to taste',
      ],
      steps: [
        'Heat butter. Sauté onion until golden, about 8 minutes.',
        'Add ginger and garlic. Cook 2 minutes until fragrant.',
        'Add chili powder and coriander. Stir 30 seconds.',
        'Add tomato puree. Cook on medium-high 10 minutes until oil separates at edges.',
        'Let cool slightly, then blend the sauce until smooth. Return to pan.',
        'Stir in Greek yogurt slowly to prevent curdling. Simmer 5 minutes.',
        'Add paneer cubes, honey, garam masala, and crushed kasuri methi.',
        'Simmer 5 more minutes. Serve with brown rice.',
      ],
    },
    {
      id: 15,
      name: 'Black Bean Veggie Burger Wrap',
      cuisine: 'Quick',
      prepTime: 15,
      cookTime: 15,
      protein: 20,
      cal: 490,
      highProtein: true,
      quickMake: true,
      ingredients: [
        '1 can (15 oz) black beans, drained and rinsed',
        '1/4 cup rolled oats',
        '1/4 cup finely diced onion',
        '2 garlic cloves, minced',
        '1 tsp cumin',
        '1 tsp smoked paprika',
        'Salt and pepper to taste',
        '1 large whole wheat tortilla',
        '1/4 cup salsa',
        '2 tbsp Greek yogurt or sour cream',
        'Shredded lettuce, sliced avocado, tomato',
      ],
      steps: [
        'Mash black beans in a bowl, leaving some texture.',
        'Mix in oats, onion, garlic, cumin, paprika, salt, and pepper.',
        'Form into 2 patties. Refrigerate 10 minutes to firm up.',
        'Heat a non-stick pan over medium heat with a tiny bit of oil.',
        'Cook patties 4–5 minutes per side until firm and golden.',
        'Warm tortilla on a dry pan.',
        'Assemble wrap: Greek yogurt, shredded lettuce, tomato, avocado, black bean patty, and salsa.',
        'Roll tightly, cut in half, serve immediately.',
      ],
    },
    {
      id: 16,
      name: 'Rava Upma + Paneer Scramble',
      cuisine: 'South Indian',
      prepTime: 10,
      cookTime: 20,
      protein: 20,
      cal: 380,
      highProtein: true,
      quickMake: false,
      ingredients: [
        '3/4 cup semolina (rava/sooji)',
        '1.5 cups water + 1/2 cup milk',
        '100g paneer, crumbled',
        '1 tsp mustard seeds',
        '8 curry leaves',
        '1 medium onion, diced',
        '1 green chili, minced',
        '2 tbsp cashews',
        '1/4 tsp turmeric',
        '1 tbsp ghee or oil',
        'Salt, lemon juice to taste, cilantro to garnish',
      ],
      steps: [
        'Dry roast semolina in a pan over medium heat 4–5 minutes, stirring until fragrant. Set aside.',
        'Heat ghee in same pan. Fry cashews until golden, set aside.',
        'Add mustard seeds and let them pop. Add curry leaves, green chili, and onion.',
        'Sauté onion until translucent. Add turmeric.',
        'Pour in water and milk. Bring to a boil.',
        'Add roasted rava slowly while stirring to prevent lumps.',
        'Cook on low, stirring, until upma sets (3–4 minutes). Add crumbled paneer and mix.',
        'Season with salt and lemon juice. Top with fried cashews and cilantro. Serve with coconut chutney.',
      ],
    },
    {
      id: 17,
      name: 'Italian Shirataki Tomato-Lentil',
      cuisine: 'Italian',
      prepTime: 10,
      cookTime: 25,
      protein: 22,
      cal: 380,
      highProtein: true,
      quickMake: false,
      ingredients: [
        '2 packs shirataki noodles, rinsed and dry-toasted',
        '1/2 cup red lentils, rinsed',
        '1 can (14 oz) crushed tomatoes',
        '3 garlic cloves, minced',
        '1 medium onion, finely diced',
        '1 tsp Italian seasoning',
        '1/2 tsp smoked paprika',
        '2 tbsp olive oil',
        '1.5 cups vegetable broth',
        '3 tbsp grated parmesan',
        'Fresh basil, salt and pepper',
      ],
      steps: [
        'Heat olive oil. Sauté onion 5 minutes until soft. Add garlic and cook 1 minute.',
        'Add Italian seasoning and paprika. Stir 30 seconds.',
        'Add red lentils, crushed tomatoes, and vegetable broth. Bring to a simmer.',
        'Cook 18–20 minutes until lentils are completely tender and sauce thickens.',
        'Season with salt and pepper. Stir in fresh basil.',
        'Dry-toast shirataki noodles in a dry skillet over high heat.',
        'Serve noodles topped with tomato-lentil sauce and parmesan. Garnish with extra basil.',
      ],
    },
    {
      id: 18,
      name: 'Thai Green Curry with Paneer',
      cuisine: 'Thai',
      prepTime: 15,
      cookTime: 25,
      protein: 24,
      cal: 420,
      highProtein: true,
      quickMake: false,
      ingredients: [
        '250g paneer, cubed and lightly pan-fried',
        '1 can (14 oz) light coconut milk',
        '2 tbsp green curry paste',
        '1 cup cauliflower rice (fresh or frozen)',
        '1 zucchini, sliced',
        '1 bell pepper, sliced',
        '1/2 cup green peas',
        '1 tbsp coconut oil',
        '2 kaffir lime leaves (optional)',
        '1 tbsp soy sauce or tamari',
        'Thai basil, lime juice to serve',
      ],
      steps: [
        'Make cauliflower rice: pulse raw cauliflower in food processor or buy pre-made. Sauté in a dry pan 5 minutes.',
        'Heat coconut oil in a wide pan over medium heat. Fry green curry paste 2 minutes until fragrant.',
        'Add coconut milk and kaffir lime leaves. Bring to a simmer.',
        'Add zucchini, bell pepper, and peas. Cook 8 minutes.',
        'Add pan-fried paneer cubes. Stir in soy sauce.',
        'Simmer 5 more minutes until vegetables are tender.',
        'Serve over cauliflower rice. Finish with Thai basil and a squeeze of lime.',
      ],
    },
    {
      id: 19,
      name: 'Dal Makhani Lite',
      cuisine: 'Indian',
      prepTime: 15,
      cookTime: 45,
      protein: 20,
      cal: 450,
      highProtein: false,
      quickMake: false,
      ingredients: [
        '3/4 cup whole black lentils (urad dal), soaked overnight',
        '1/4 cup kidney beans (rajma), soaked overnight',
        '2 medium tomatoes, pureed',
        '1 medium onion, finely diced',
        '3 garlic cloves, minced',
        '1-inch ginger, grated',
        '2 tbsp Greek yogurt (replaces cream)',
        '1 tbsp butter',
        '1 tsp each: cumin, coriander, kashmiri chili powder',
        '1/2 tsp garam masala',
        'Salt, kasuri methi, cilantro',
      ],
      steps: [
        'Pressure cook soaked lentils and beans with water and salt until very soft (3–4 whistles or 30 mins).',
        'Heat butter in a deep pan. Sauté onion until deeply golden, about 10 minutes.',
        'Add ginger and garlic, cook 2 minutes. Add all spices except garam masala.',
        'Add tomato puree. Cook on medium-high 12 minutes until oil separates.',
        'Add cooked dal and beans. Mix well. Add 1/2 cup water if too thick.',
        'Simmer on very low heat 20 minutes, stirring often.',
        'Stir in Greek yogurt slowly. Add garam masala and crushed kasuri methi.',
        'Serve with jeera rice. Garnish with cilantro.',
      ],
    },
    {
      id: 20,
      name: 'Shirataki Pesto Noodles',
      cuisine: 'Italian',
      prepTime: 10,
      cookTime: 10,
      protein: 18,
      cal: 340,
      highProtein: false,
      quickMake: true,
      ingredients: [
        '2 packs shirataki noodles, rinsed and dry-toasted',
        '3 tbsp basil pesto (store-bought or homemade)',
        '1 cup cherry tomatoes, halved',
        '100g paneer, cubed and pan-fried',
        '2 tbsp pine nuts or walnuts, toasted',
        '2 garlic cloves, minced',
        '1 tbsp olive oil',
        '2 tbsp grated parmesan',
        'Fresh basil, salt and pepper',
      ],
      steps: [
        'Dry-toast shirataki noodles in a dry skillet over high heat 5 minutes until most moisture evaporates.',
        'Heat olive oil in a pan. Sauté garlic 1 minute. Add cherry tomatoes and cook 3 minutes until blistered.',
        'Toss in pan-fried paneer cubes. Cook 1 minute.',
        'Add shirataki noodles and pesto. Toss everything together over medium heat.',
        'Season with salt and pepper. Heat through 2 minutes.',
        'Serve topped with toasted pine nuts, parmesan, and fresh basil.',
      ],
    },
    {
      id: 21,
      name: 'Masala Dosa Crepes',
      cuisine: 'South Indian',
      prepTime: 15,
      cookTime: 25,
      protein: 16,
      cal: 380,
      highProtein: false,
      quickMake: false,
      ingredients: [
        '4 large whole wheat flour tortillas (used as crepes)',
        '3 medium potatoes, boiled and mashed',
        '1 medium onion, sliced',
        '1/2 tsp mustard seeds',
        '8 curry leaves',
        '1/4 tsp turmeric',
        '1 green chili, minced',
        '1 tbsp oil',
        'Salt to taste',
        'Coconut chutney for serving',
        'Sambar for serving',
      ],
      steps: [
        'Heat oil. Add mustard seeds and let them pop. Add curry leaves and green chili.',
        'Add sliced onion and sauté until golden, about 8 minutes.',
        'Add turmeric and mashed potatoes. Mix well. Season with salt.',
        'Cook the potato filling together 3 minutes until well combined.',
        'Warm whole wheat tortillas on a hot tawa — they serve as the "crepe" base.',
        'Place a portion of filling on each crepe. Fold into a half-moon or roll.',
        'Serve immediately with coconut chutney and sambar on the side.',
      ],
    },
    {
      id: 22,
      name: 'Paneer Stir Fry Soy-Ginger',
      cuisine: 'Indian',
      prepTime: 10,
      cookTime: 15,
      protein: 26,
      cal: 440,
      highProtein: true,
      quickMake: true,
      ingredients: [
        '250g paneer, cut into thin strips',
        '1 red bell pepper, sliced',
        '1 green bell pepper, sliced',
        '1 yellow bell pepper, sliced',
        '3 tbsp soy sauce or tamari',
        '1 tbsp rice vinegar',
        '1 tsp sesame oil',
        '1 tsp honey',
        '2-inch ginger, grated',
        '3 garlic cloves, minced',
        '1 tbsp oil',
        '1 cup cooked brown rice, sesame seeds to garnish',
      ],
      steps: [
        'Whisk soy sauce, rice vinegar, sesame oil, honey, ginger, and garlic into sauce.',
        'Heat oil in a wok or large skillet over very high heat.',
        'Add paneer strips. Stir-fry 3–4 minutes until golden on edges.',
        'Push paneer to side. Add bell peppers. Stir-fry 2 minutes — keep them crisp.',
        'Pour sauce over everything. Toss to coat. Cook 2 minutes until sauce glazes the paneer.',
        'Serve over brown rice. Garnish with sesame seeds and green onions.',
      ],
    },
    {
      id: 23,
      name: 'Mediterranean Quinoa Bowl',
      cuisine: 'Quick',
      prepTime: 10,
      cookTime: 15,
      protein: 20,
      cal: 430,
      highProtein: true,
      quickMake: false,
      ingredients: [
        '1/2 cup dry quinoa, rinsed',
        '1 cup vegetable broth',
        '1/2 cup canned chickpeas, drained',
        '1/2 cup cherry tomatoes, halved',
        '1/2 cucumber, diced',
        '1/4 cup kalamata olives (optional)',
        '3 tbsp crumbled feta',
        '2 tbsp hummus',
        '1 tbsp olive oil + lemon juice',
        '1 tsp dried oregano',
        'Fresh parsley, salt and pepper',
      ],
      steps: [
        'Cook quinoa in vegetable broth per package directions. Cool slightly.',
        'Season chickpeas with olive oil, oregano, salt. Either eat as-is or roast at 400°F for 15 minutes.',
        'Prepare all vegetables.',
        'Assemble bowl: quinoa base, chickpeas, tomatoes, cucumber, olives.',
        'Add a dollop of hummus and crumble feta on top.',
        'Drizzle with olive oil and lemon juice. Season with salt and pepper.',
        'Garnish with parsley. Toss before eating or enjoy as arranged.',
      ],
    },
    {
      id: 24,
      name: 'Chole Chickpea Curry',
      cuisine: 'Indian',
      prepTime: 10,
      cookTime: 30,
      protein: 18,
      cal: 420,
      highProtein: false,
      quickMake: false,
      ingredients: [
        '2 cans (15 oz each) chickpeas, drained',
        '2 medium tomatoes, pureed',
        '1 large onion, finely diced',
        '3 garlic cloves, minced',
        '1-inch ginger, grated',
        '2 tsp chole masala or garam masala',
        '1 tsp each: cumin, coriander, chili powder',
        '1/2 tsp turmeric',
        '1 tbsp oil',
        '1/2 cup water',
        'Salt, amchur (dry mango powder), cilantro',
      ],
      steps: [
        'Heat oil. Sauté onion over medium heat until deeply golden brown, about 12 minutes.',
        'Add ginger and garlic. Cook 2 minutes.',
        'Add all dry spices. Stir 30 seconds — mixture will be dry.',
        'Add tomato puree. Cook 8–10 minutes until oil separates at the edges.',
        'Add chickpeas and water. Mash a handful of chickpeas against the pot to thicken the gravy.',
        'Simmer 15 minutes. Add amchur for tanginess.',
        'Season with salt. Garnish with cilantro. Serve with brown rice.',
      ],
    },
    {
      id: 25,
      name: 'Palak Paneer Lite',
      cuisine: 'Indian',
      prepTime: 15,
      cookTime: 20,
      protein: 26,
      cal: 460,
      highProtein: true,
      quickMake: false,
      ingredients: [
        '200g paneer, cubed',
        '4 cups baby spinach (or 2 bunches regular spinach)',
        '1 medium onion, diced',
        '2 garlic cloves, minced',
        '1-inch ginger, grated',
        '1 green chili',
        '1/2 cup plain Greek yogurt (replaces cream)',
        '1 medium tomato, chopped',
        '1 tsp cumin seeds',
        '1/2 tsp each: coriander, garam masala',
        '1/4 tsp turmeric',
        '1 tbsp ghee or oil',
        'Salt, lemon juice to taste',
      ],
      steps: [
        'Blanch spinach in boiling water 2 minutes. Drain, rinse in cold water, squeeze dry.',
        'Blend spinach with green chili to a smooth puree. Set aside.',
        'Pan-fry paneer cubes in a little oil until golden on 2 sides. Set aside.',
        'Heat ghee. Add cumin seeds, then onion. Sauté until golden.',
        'Add ginger and garlic. Cook 2 minutes. Add tomato and cook until soft.',
        'Add all spices. Stir 30 seconds.',
        'Add spinach puree. Cook 5 minutes on medium heat.',
        'Stir in Greek yogurt slowly. Add paneer. Season with salt and lemon juice. Simmer 3 minutes. Serve with roti.',
      ],
    },
  ];

})();
